/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderLayer.h>

#import "BRMenuItemLayerProtocol.h"

@class BRImageLayer, BRTextMenuItemLayer;

@interface BRAdornedMenuItemLayer : BRRenderLayer <BRMenuItemLayer>
{
    BRTextMenuItemLayer *_textItem;	// 56 = 0x38
    BRImageLayer *_leftImage;	// 60 = 0x3c
    BRImageLayer *_leftImageHighlighted;	// 64 = 0x40
    BRImageLayer *_rightImage;	// 68 = 0x44
    BRImageLayer *_rightImageHighlighted;	// 72 = 0x48
    BRImageLayer *_textImage;	// 76 = 0x4c
    float _dimValue;	// 80 = 0x50
    float _rightIconXFactor;	// 84 = 0x54
    float _rightIconScaleFactor;	// 88 = 0x58
}

+ (id)adornedMenuItemWithScene:(id)fp8;
+ (id)adornedShuffleMenuItemWithScene:(id)fp8;
+ (id)adornedFolderMenuItemWithScene:(id)fp8;
+ (id)adornedNetworkMenuItemWithScene:(id)fp8;
- (void)setTextItem:(id)fp8;
- (void)dealloc;
- (void)setAlphaValue:(float)fp8;
- (void)setFrame:(struct _NSRect)fp8;
- (id)textItem;
- (id)title;
- (void)setLeftIcon:(id)fp8;
- (void)setLeftIcon:(id)fp8 andHighlightedVersion:(id)fp12;
- (void)setRightIcon:(id)fp8;
- (void)setRightIcon:(id)fp8 andHighlightedVersion:(id)fp12;
- (void)setRightIcon:(id)fp8 andHighlightedVersion:(id)fp12 xFactor:(float)fp16 scaleFactor:(float)fp20;
- (void)setTextIcon:(id)fp8 xFactor:(float)fp12 scaleFactor:(float)fp16;
- (void)highlight;
- (void)unHighlight;
- (void)scrollItemIfNecessary;
- (void)stopScrollingItem;
- (void)setDimValue:(float)fp8;

@end

