/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSDictionary;

@interface BRAirportNetwork : NSObject
{
    NSDictionary *_data;	// 4 = 0x4
}

+ (id)networkWithName:(id)fp8 error:(id *)fp12;
+ (id)networkWithDictionary:(id)fp8;
+ (BOOL)openApple80211Ref:(struct _Apple80211 **)fp8 error:(int *)fp12;
+ (void)checkAirportPower;
- (id)init;
- (void)dealloc;
- (id)name;
- (BOOL)usesWPAPrivacy;
- (BOOL)usesWEPPrivacy;
- (BOOL)associateUsingPassword:(id)fp8 error:(id *)fp12;

@end

