/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRLayerController.h>

@class BRGoBackControl, BRHeaderControl, BRImageControl, BRTextControl;

@interface BRAlertController : BRLayerController
{
    id _eventDelegate;	// 24 = 0x18
    SEL _eventSelector;	// 28 = 0x1c
    BRHeaderControl *_header;	// 32 = 0x20
    int _type;	// 36 = 0x24
    BRTextControl *_primary;	// 40 = 0x28
    BRTextControl *_secondary;	// 44 = 0x2c
    BRImageControl *_image;	// 48 = 0x30
    BRGoBackControl *_goBack;	// 52 = 0x34
}

+ (id)alertForError:(id)fp8 withScene:(id)fp12;
+ (id)alertOfType:(int)fp8 titled:(id)fp12 primaryText:(id)fp16 secondaryText:(id)fp20 withScene:(id)fp24;
- (id)initWithType:(int)fp8 titled:(id)fp12 primaryText:(id)fp16 secondaryText:(id)fp20 withScene:(id)fp24;
- (void)dealloc;
- (BOOL)brEventAction:(id)fp8;
- (void)wasPushed;
- (void)setTitle:(id)fp8;
- (void)setPrimaryText:(id)fp8;
- (void)setPrimaryText:(id)fp8 withAttributes:(id)fp12;
- (void)setSecondaryText:(id)fp8;
- (void)setSecondaryText:(id)fp8 withAttributes:(id)fp12;
- (void)setHasGoBackControl:(BOOL)fp8;
- (void)setEventDelegate:(id)fp8 selector:(SEL)fp12;

@end

