/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRLayerController.h>

#import "BRTextEntryDelegateProtocol.h"

@class BRAirportNetwork, BRTextEntryControl;

@interface BRAPPasswordEntryController : BRLayerController <BRTextEntryDelegate>
{
    BRAirportNetwork *_network;	// 24 = 0x18
    id _delegate;	// 28 = 0x1c
    BRTextEntryControl *_editor;	// 32 = 0x20
}

- (id)initForNetwork:(id)fp8 withScene:(id)fp12 acceptOnlyHex:(BOOL)fp16 showBack:(BOOL)fp20 notifying:(id)fp24;
- (void)dealloc;
- (void)textDidChange:(id)fp8;
- (void)textDidEndEditing:(id)fp8;
- (void)setInitialPassword:(id)fp8;

@end

