/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRAPNetworkMenuController.h>

#import "BRAPPasswordEntryDelegateProtocol.h"

@interface BRAPNetworkMenuController (PasswordEntry) <BRAPPasswordEntryDelegate>
- (void)passwordEntered:(id)fp8 forNetwork:(id)fp12;
@end

