/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import "BRApplianceProtocolProtocol.h"

@class NSBundle;

@interface BRAppliance : NSObject <BRApplianceProtocol>
{
    NSBundle *_myBundle;	// 4 = 0x4
}

- (id)init;
- (void)dealloc;
- (id)version;
- (id)applianceKey;
- (id)applianceName;
- (float)applianceIconReflectionOffset;
- (float)applianceIconHorizontalOffset;
- (float)applianceIconKerningFactor;
- (id)applianceControllerWithScene:(id)fp8;

@end

