/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSMutableArray;

@interface BRApplianceManager : NSObject
{
    NSMutableArray *_applianceList;	// 4 = 0x4
}

+ (id)sharedManager;
- (void)dealloc;
- (void)loadAppliances;
- (id)applianceInfoList;
- (BOOL)applianceInfo:(id)fp8 appliesToMediaHost:(id)fp12;
- (id)instantiateApplianceForInfo:(id)fp8;

@end

