/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRLayerController.h>

@class BRAirportNetwork, BRWaitSpinnerControl;

@interface BRAPTestController : BRLayerController
{
    BRWaitSpinnerControl *_spinner;	// 24 = 0x18
    BRAirportNetwork *_network;	// 28 = 0x1c
    BOOL _testFailed;	// 32 = 0x20
    id _delegate;	// 36 = 0x24
}

- (id)initForNetwork:(id)fp8 withScene:(id)fp12 showBack:(BOOL)fp16 notifying:(id)fp20;
- (void)dealloc;
- (void)wasPushed;
- (void)wasExhumedByPoppingController:(id)fp8;

@end

