/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRCenteredMenuController.h>

#import "BRAPPasswordEntryDelegateProtocol.h"
#import "BRMenuListItemProviderProtocol.h"

@class BRAirportNetwork;

@interface BRAPWEPPasswordMenuController : BRCenteredMenuController <BRMenuListItemProvider, BRAPPasswordEntryDelegate>
{
    BRAirportNetwork *_network;	// 136 = 0x88
    long _passwordType;	// 140 = 0x8c
    id _delegate;	// 144 = 0x90
}

- (id)initForNetwork:(id)fp8 withScene:(id)fp12 showBack:(BOOL)fp16 notifying:(id)fp20;
- (void)dealloc;
- (void)itemSelected:(long)fp8;
- (id)itemForRow:(long)fp8;
- (long)itemCount;
- (id)titleForRow:(long)fp8;
- (long)rowForTitle:(id)fp8;
- (void)passwordEntered:(id)fp8 forNetwork:(id)fp12;

@end

