/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRAPTestController.h>

@interface BRAPTestController (Private)
- (void)_testInternetConnection;
- (void)_testFinished:(id)fp8;
- (void)_showProgress;
- (void)_hideProgress;
@end

