/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRAPNetworkMenuController.h>

#import "BRAPTestResultDelegateProtocol.h"

@interface BRAPNetworkMenuController (NetworkTest) <BRAPTestResultDelegate>
- (void)testCompleted:(BOOL)fp8;
@end

