/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRLayerController.h>

@class BRTextEntryControl;

@interface BRAPNameEntryController : BRLayerController
{
    BRTextEntryControl *_editor;	// 24 = 0x18
}

- (id)initWithScene:(id)fp8 showBack:(BOOL)fp12;
- (void)dealloc;
- (void)setEntryDelegate:(id)fp8;

@end

