/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@interface BRAppManager : NSObject
{
    struct __CFRunLoop *_mainRunLoop;	// 4 = 0x4
    BOOL _isTerminating;	// 8 = 0x8
}

+ (id)sharedApplication;
- (void)terminate;
- (BOOL)isTerminating;
- (BOOL)enableITMS;
- (void)run;
- (void)postNotificationOnMainThread:(id)fp8;
- (void)_postNotification:(id)fp8;

@end

