/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSArray, NSLock, NSMutableArray, NSMutableDictionary, NSString;

@interface BRAssetArtLoader : NSObject
{
    long _queueSize;	// 4 = 0x4
    NSMutableArray *_imageQueue;	// 8 = 0x8
    NSMutableDictionary *_candidateAssets;	// 12 = 0xc
    NSArray *_filteredAssets;	// 16 = 0x10
    unsigned int _randomize:1;	// 20 = 0x14
    unsigned int _unevenSegments:1;	// 20 = 0x14
    NSString *_lastAssetArtID;	// 24 = 0x18
    NSMutableDictionary *_pendingAssets;	// 28 = 0x1c
    NSLock *_queueLock;	// 32 = 0x20
    long _serialIndex;	// 36 = 0x24
    long _imageArrayIndex;	// 40 = 0x28
    long _segmentLength;	// 44 = 0x2c
    long _segmentCount;	// 48 = 0x30
    long _imageCount;	// 52 = 0x34
    int _fillStrategy;	// 56 = 0x38
}

- (id)init;
- (void)dealloc;
- (void)setSegmentCount:(long)fp8;
- (long)segmentCount;
- (void)setAssets:(id)fp8;
- (void)setFillStrategy:(int)fp8;
- (int)fillStrategy;
- (void)setQueueSize:(long)fp8;
- (long)queueSize;
- (void)flushQueue;
- (BOOL)queueReady;
- (void)setRandomize:(BOOL)fp8;
- (BOOL)randomize;
- (long)imageCount;
- (id)finalFormForImage:(struct CGImage *)fp8;
- (id)nextImage;
- (void)abandonPendingAssetWithCoverArtID:(id)fp8;
- (void)promoteCandidateAssetWithID:(id)fp8 toPendingAssetWithCoverArtID:(id)fp12;
- (void)enqueueImage:(id)fp8 forAssetWithCoverArtID:(id)fp12;

@end

