/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import "BRMediaLoadingProtocol.h"
#import "BRMediaProviderProtocol.h"

@interface BRBaseMediaProvider : NSObject <BRMediaProvider, BRMediaLoading>
{
    int _providerStatus;	// 4 = 0x4
}

+ (id)errorStateOfProvider:(id)fp8;
+ (id)mediaProvider;
- (void)dealloc;
- (id)providerID;
- (id)machineID;
- (id)providerName;
- (id)mediaTypes;
- (id)mediaForEntityName:(id)fp8;
- (id)objectsWithEntityName:(id)fp8 qualifiedByPredicate:(id)fp12 sortDescriptors:(id)fp16 error:(id *)fp20;
- (int)status;
- (int)errorCodeForProvider;
- (void)setStatus:(int)fp8;
- (int)load;
- (int)unload;
- (BOOL)autoload;
- (void)reset;

@end

