/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import "BRMediaCollectionProtocol.h"

@interface BRBaseMediaCollection : NSObject <BRMediaCollection>
{
    id _provider;	// 4 = 0x4
}

- (id)initWithMediaProvider:(id)fp8;
- (void)dealloc;
- (id)provider;
- (id)childCollections;
- (id)parentCollection;
- (id)collectionType;
- (id)collectionID;
- (struct CGImage *)coverArt;
- (BOOL)hasCoverArt;
- (int)count;
- (id)mediaAssets;
- (BOOL)isCompilation;
- (BOOL)isSingleArtistCompilation;
- (id)artist;
- (id)title;
- (long)duration;
- (id)mediaType;
- (BOOL)isLocal;
- (struct CGImage *)coverArtNoDefault;

@end

