/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRBitmapTexture.h>

@interface BRBitmapTexture (TextureManagement)
- (void)_generateTexture:(BOOL)fp8;
- (void)_generateRectangleTexture;
- (void)_generateMipmappedTexture;
- (void)_destroyTexture;
@end

