/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRBlackScreenRecoveryController.h>

@interface BRBlackScreenRecoveryController (BlackScreenRecovery)
- (id)_nextModeToTry;
- (id)_countDownString;
- (void)_modeTimerCallback:(id)fp8;
- (void)_restoreOriginalMode;
- (void)_setIsOneShot:(BOOL)fp8;
- (BOOL)_isOneShot;
- (void)_popBSRController;
@end

