/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import "BRScreenSaverPluginProtocolProtocol.h"

@class BRQuadLayer;

@interface BRBlackScreenSaver : NSObject <BRScreenSaverPluginProtocol>
{
    BRQuadLayer *_blackShroudOfDeath;	// 4 = 0x4
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (id)layer;
- (void)activate;
- (void)deactivate;

@end

