/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderLayer.h>

@class BRImageLayer, BRTextLayer;

@interface BRBlackScreenRecoveryLayer : BRRenderLayer
{
    BRImageLayer *_appleLogo;	// 56 = 0x38
    BRTextLayer *_currentResolutionLabel;	// 60 = 0x3c
    BRTextLayer *_countDownToNextResolutionLabel;	// 64 = 0x40
    BRTextLayer *_canYouSeeTheAppleLogoLabel;	// 68 = 0x44
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)setFrame:(struct _NSRect)fp8;
- (void)setCurrentResolutionString:(id)fp8;
- (void)setSecondsLeftBeforeNextDisplayModeChangeString:(id)fp8;
- (void)setSolutionText:(id)fp8;

@end

