/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMenuController.h>

#import "BRMenuListItemProviderProtocol.h"

@class BRBlackFadeoutLayer, BRBlackScreenRecoveryLayer, BRLayerController, BRRenderLayer, BRRootLayer, NSArray, NSDictionary, NSTimer;

@interface BRBlackScreenRecoveryController : BRMenuController <BRMenuListItemProvider>
{
    BRRenderLayer *_oldRootLayer;	// 64 = 0x40
    BRRootLayer *_ourRootLayer;	// 68 = 0x44
    BRBlackFadeoutLayer *_oldRootFadeInLayer;	// 72 = 0x48
    BRBlackFadeoutLayer *_ourRootFadeInLayer;	// 76 = 0x4c
    BRBlackScreenRecoveryLayer *_bsLayer;	// 80 = 0x50
    BRLayerController *_controllerToPopTo;	// 84 = 0x54
    unsigned int _popToSpecificController:1;	// 88 = 0x58
    struct _CGDirectDisplayID *_display;	// 92 = 0x5c
    int _attemptedModeNum;	// 96 = 0x60
    int _numModes;	// 100 = 0x64
    int _numCycles;	// 104 = 0x68
    unsigned int _isOneShot:1;	// 108 = 0x6c
    unsigned int _alreadyRunningBSR:1;	// 108 = 0x6c
    NSArray *_listOfResolutionsToTry;	// 112 = 0x70
    NSDictionary *_originalMode;	// 116 = 0x74
    NSTimer *_modeTimer;	// 120 = 0x78
    int _secsLeftBeforeNextDisplayMode;	// 124 = 0x7c
}

+ (id)controllerForChangingToResolution:(id)fp8 forScene:(id)fp12;
+ (id)controllerForTryingResolutions:(id)fp8 forScene:(id)fp12;
- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)resetLayout;
- (void)willBePushed;
- (void)wasPushed;
- (void)willBePopped;
- (void)wasPopped;
- (BOOL)brEventAction:(id)fp8;
- (struct _NSRect)listFrameForBounds:(struct _NSSize)fp8;
- (void)frameForTitleIcon:(struct _NSRect *)fp8 andText:(struct _NSRect *)fp12 forBounds:(struct _NSSize)fp16;
- (void)itemSelected:(long)fp8;
- (id)itemForRow:(long)fp8;
- (long)itemCount;
- (id)titleForRow:(long)fp8;
- (long)rowForTitle:(id)fp8;
- (void)setListOfResolutionsToTry:(id)fp8;
- (void)setControllerToPopTo:(id)fp8;

@end

