/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRBlurryImageLayer.h>

@interface BRBlurryImageLayer (TextureRendering)
- (void)_renderTexture:(id)fp8 withReflection:(id)fp12 flipReflection:(BOOL)fp16 sizeFactor:(float)fp20 alpha:(float)fp24;
@end

