/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRRenderLayer, BRSelectionLozengeLayer, BRTextLayer;

@interface BRButtonControl : BRControl
{
    BRRenderLayer *_layer;	// 8 = 0x8
    BRTextLayer *_title;	// 12 = 0xc
    BRSelectionLozengeLayer *_lozenge;	// 16 = 0x10
    SEL _action;	// 20 = 0x14
    id _target;	// 24 = 0x18
    int _alignment;	// 28 = 0x1c
    int _textAlignment;	// 32 = 0x20
}

- (id)initWithScene:(id)fp8 masterLayerSize:(struct _NSSize)fp12;
- (void)dealloc;
- (id)layer;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setAction:(SEL)fp8;
- (SEL)action;
- (void)setTarget:(id)fp8;
- (id)target;
- (void)setAlignment:(int)fp8;
- (int)alignment;
- (void)setTextAlignment:(int)fp8;
- (int)textAlignment;
- (BOOL)brEventAction:(id)fp8;
- (void)setWidth:(float)fp8;
- (void)setYPosition:(float)fp8;

@end

