/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderLayer.h>

@class BRFrameAnimation, BRImageLayer, BRRoundRectLayer, BRRoundRectOutlineLayer, BRTextEntrySelectionWidget, NSArray;

@interface BRCharacterSelectionLayer : BRRenderLayer
{
    BRRoundRectLayer *_roundRectBackground;	// 56 = 0x38
    BRRoundRectOutlineLayer *_roundRectOutline;	// 60 = 0x3c
    NSArray *_glyphs;	// 64 = 0x40
    NSArray *_glyphRows;	// 68 = 0x44
    BRImageLayer *_backArrow;	// 72 = 0x48
    BRTextEntrySelectionWidget *_selectionWidget;	// 76 = 0x4c
    BRFrameAnimation *_selectionAnimation;	// 80 = 0x50
    struct _NSSize _cellSize;	// 84 = 0x54
    struct BRGlyphLocation _selectionLocation;	// 92 = 0x5c
}

- (id)initWithScene:(id)fp8;
- (id)initWithScene:(id)fp8 hexInputOnly:(BOOL)fp12;
- (void)dealloc;
- (BOOL)moveLeft;
- (BOOL)startContinuousLeft;
- (void)stopContinuousLeft;
- (BOOL)moveRight;
- (BOOL)startContinuousRight;
- (void)stopContinuousRight;
- (BOOL)moveDown;
- (BOOL)moveUp;
- (id)pickCurrentCharacter;
- (struct _NSRect)preferredFrameForScreenSize:(struct _NSSize)fp8;
- (struct _NSRect)textFieldFrame;
- (void)reset;
- (void)setFrame:(struct _NSRect)fp8;

@end

