/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRCharacterSelectionLayer.h>

@interface BRCharacterSelectionLayer (Framing)
- (void)_layoutUI;
- (void)_setBackArrowSize;
- (float)_cellAlignedWidthForFrame:(struct _NSRect)fp8;
- (id)_buildGlyphRows;
@end

