/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRCharacterSelectionLayer.h>

@interface BRCharacterSelectionLayer (GlyphSelection)
- (struct _NSRect)_selectionWidgetFrameForLocation:(struct BRGlyphLocation)fp8;
- (struct BRGlyphLocation)_glyphClosestTo:(struct BRGlyphLocation)fp8 inRow:(int)fp16;
- (id)_cellContentsAtLocation:(struct BRGlyphLocation)fp8;
- (id)_glyphAtLocation:(struct BRGlyphLocation)fp8;
- (void)_setSelection:(struct BRGlyphLocation)fp8 animate:(BOOL)fp16;
- (id)_stringForSelection:(struct BRGlyphLocation)fp8;
@end

