/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import "BREventResponderProtocol.h"

@class BRRenderScene;

@interface BRControl : NSObject <BREventResponder>
{
    BRRenderScene *_scene;	// 4 = 0x4
}

+ (id)controlWithScene:(id)fp8;
- (id)initWithScene:(id)fp8;
- (id)scene;
- (void)dealloc;
- (id)layer;
- (BOOL)brEventAction:(id)fp8;
- (void)setFrame:(struct _NSRect)fp8;
- (struct _NSRect)frame;
- (void)setAlphaValue:(float)fp8;
- (float)alphaValue;
- (void)setHidden:(BOOL)fp8;
- (BOOL)hidden;

@end

