/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRLayoutManager.h>

@interface BRColumnLayoutManager : BRLayoutManager
{
    float _verticalGap;	// 24 = 0x18
    float _horizontalBorder;	// 28 = 0x1c
    float _verticalBorder;	// 32 = 0x20
    int _alignment;	// 36 = 0x24
}

- (id)init;
- (void)layoutControls;
- (void)setVerticalGap:(float)fp8;
- (float)verticalGap;
- (void)setHorizontalBorder:(float)fp8;
- (float)horizontalBorder;
- (void)setVerticalBorder:(float)fp8;
- (float)verticalBorder;
- (void)setColumnAlignment:(int)fp8;

@end

