/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRCoreGraphicsLayer.h>

@interface BRCoreGraphicsLayer (TextureHandling)
- (void)_texturizeCGDrawing;
- (void)_releaseResources;
@end

