/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import "BREventResponderProtocol.h"

@class NSMutableArray;

@interface BRControllerStack : NSObject <BREventResponder>
{
    NSMutableArray *_stack;	// 4 = 0x4
    unsigned int _animationsDisabled:1;	// 8 = 0x8
    unsigned int _dumpStack:1;	// 8 = 0x8
}

- (id)init;
- (void)dealloc;
- (void)pushController:(id)fp8;
- (void)popController;
- (void)popToController:(id)fp8;
- (void)popToControllerOfClass:(Class)fp8;
- (void)popToControllerWithLabel:(id)fp8;
- (void)swapController:(id)fp8;
- (id)peekController;
- (BOOL)brEventAction:(id)fp8;
- (id)controllerLabelled:(id)fp8;
- (void)replaceControllersAboveLabel:(id)fp8 withController:(id)fp12;
- (void)resizeControllers;
- (int)count;

@end

