/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRCoreImageTexture.h>

@interface BRCoreImageTexture (ImageGeneration)
- (void)_generateBufferForImage:(id)fp8;
- (void)_renderImageToBuffer:(id)fp8 bufferContext:(struct _CGLContextObject *)fp12;
- (void)_generateTexture;
@end

