/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import "BRMediaPreviewControllerProtocol.h"

@class BRAggregateAnimation, BRImageLayer, BRMediaType, BRRenderLayer, BRRenderScene, NSArray, NSMutableArray, NSTimer;

@interface BRCoverArtPreviewController : NSObject <BRMediaPreviewController>
{
    NSArray *_assets;	// 4 = 0x4
    NSMutableArray *_availableImages;	// 8 = 0x8
    BRMediaType *_mediaType;	// 12 = 0xc
    BRRenderScene *_scene;	// 16 = 0x10
    BRRenderLayer *_mainLayer;	// 20 = 0x14
    BRImageLayer *_coverArtLayerA;	// 24 = 0x18
    BRImageLayer *_coverArtLayerB;	// 28 = 0x1c
    BRImageLayer *_frontmostLayer;	// 32 = 0x20
    BRImageLayer *_backmostLayer;	// 36 = 0x24
    BRAggregateAnimation *_crossfadeAnim;	// 40 = 0x28
    NSTimer *_crossfadeTimer;	// 44 = 0x2c
    long _imageIndex;	// 48 = 0x30
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)setAsset:(id)fp8;
- (void)setAssets:(id)fp8;
- (void)setMissingAssetType:(id)fp8;
- (id)layer;
- (void)activate;
- (void)willLoseFocus;
- (void)willRegainFocus;
- (void)willDeactivate;
- (void)deactivate;
- (BOOL)fadeLayerIn;

@end

