/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSArray, NSLock, NSPredicate, NSSet, NSString;

@interface BRDataStore : NSObject
{
    NSLock *_dataLock;	// 4 = 0x4
    NSString *_entityName;	// 8 = 0x8
    NSPredicate *_predicate;	// 12 = 0xc
    NSSet *_mediaTypes;	// 16 = 0x10
    NSArray *_descriptors;	// 20 = 0x14
    NSArray *_cache;	// 24 = 0x18
    BOOL _cacheResults;	// 28 = 0x1c
}

- (id)initWithEntityName:(id)fp8 predicate:(id)fp12 mediaTypes:(id)fp16;
- (id)initWithEntityName:(id)fp8 predicate:(id)fp12 mediaTypes:(id)fp16 shouldCacheResults:(BOOL)fp20;
- (void)dealloc;
- (void)setSortDescriptors:(id)fp8;
- (void)purge;
- (id)data;
- (id)dataReportingError:(id *)fp8;

@end

