/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@interface BRDisplayChangedData : NSObject
{
    struct _CGDirectDisplayID *_display;	// 4 = 0x4
    unsigned int _flags;	// 8 = 0x8
}

- (id)initWithDisplay:(struct _CGDirectDisplayID *)fp8 andFlags:(unsigned int)fp12;
- (struct _CGDirectDisplayID *)display;
- (unsigned int)flags;

@end

