/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@class NSTimer;

@interface BRDisplayManager : BRSingleton
{
    struct _CGDirectDisplayID *_display;	// 4 = 0x4
    struct _NSSize _renderingSize;	// 8 = 0x8
    unsigned int _listenForEvents:1;	// 16 = 0x10
    unsigned int _fadeToken;	// 20 = 0x14
    NSTimer *_fadeInTimer;	// 24 = 0x18
}

+ (id)singleton;
+ (void)setSingleton:(id)fp8;
+ (id)currentDisplayModeUIString;
+ (id)uiStringForDisplayMode:(id)fp8;
- (id)init;
- (void)dealloc;
- (struct _CGDirectDisplayID *)display;
- (int)connectionType;
- (id)connectionTypeDescriptionForDisplay:(struct _CGDirectDisplayID *)fp8;
- (float)refreshRate;
- (BOOL)interlaced;
- (BOOL)displayOnline;
- (BOOL)displayConfigured;
- (struct _NSSize)renderingSize;
- (BOOL)needsGLUpscaling;
- (BOOL)setDisplayMode:(id)fp8;
- (id)displayMode;
- (id)stringForDisplayMode:(id)fp8;
- (id)displayModeMostLikelySafeForCurrentDisplay;
- (id)displayModeForString:(id)fp8 modeSafe:(char *)fp12;
- (id)displayModeNearString:(id)fp8 mustBeSafe:(BOOL)fp12;
- (BOOL)displayModeSafe:(id)fp8;
- (id)listOfSafeSupportedModes;
- (BOOL)displayModeSupported:(id)fp8;
- (id)listOfAllSupportedModes;
- (void)checkDisplayConfiguration:(char *)fp8;
- (void)captureAllDisplays;
- (void)releaseAllDisplays;

@end

