/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRDisplayManager.h>

@interface BRDisplayManager (DisplayHandling)
- (struct _CGDirectDisplayID *)_displayIDToUse;
- (BOOL)_displayValid:(struct _CGDirectDisplayID *)fp8;
@end

