/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRLayerController.h>

@class BRButtonControl, BRHeaderControl, BRVerticalScrollControl;

@interface BRDocumentController : BRLayerController
{
    BRHeaderControl *_header;	// 24 = 0x18
    BRVerticalScrollControl *_verticalScroll;	// 28 = 0x1c
    BRButtonControl *_button;	// 32 = 0x20
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)setButtonTitle:(id)fp8 action:(SEL)fp12 target:(id)fp16;
- (void)setHeaderTitle:(id)fp8;
- (struct _NSSize)_scrollSizeForMasterFrame:(struct _NSRect)fp8;
- (void)setHeaderIcon:(id)fp8 horizontalOffset:(float)fp12 kerningFactor:(float)fp16;
- (void)setDocumentPath:(id)fp8 encoding:(unsigned int)fp12;
- (void)setDocumentPath:(id)fp8;
- (void)doLayout;

@end

