/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRLayerController.h>

#import "BRTextEntryDelegateProtocol.h"

@class BRHeaderControl, NSString;

@interface BRDottedQuadEntryController : BRLayerController <BRTextEntryDelegate>
{
    id _delegate;	// 24 = 0x18
    BRHeaderControl *_header;	// 28 = 0x1c
    NSString *_dottedQuad;	// 32 = 0x20
}

- (id)initWithScene:(id)fp8 showingTitle:(id)fp12 prompt:(id)fp16 label:(id)fp20 notifying:(id)fp24;
- (void)dealloc;
- (void)setIcon:(id)fp8 horizontalOffset:(float)fp12 kerningFactor:(float)fp16;
- (void)textDidChange:(id)fp8;
- (void)textDidEndEditing:(id)fp8;
- (id)dottedQuad;

@end

