/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderLayer.h>

@class NSAttributedString, NSString;

@interface BRErrorLayer : BRRenderLayer
{
    NSString *_title;	// 56 = 0x38
    NSAttributedString *_alertRef;	// 60 = 0x3c
    NSAttributedString *_messageRef;	// 64 = 0x40
}

- (void)dealloc;
- (void)setFrame:(struct _NSRect)fp8;
- (void)setTitle:(id)fp8;
- (void)setFailureReason:(id)fp8;
- (void)setRecoverySuggestion:(id)fp8;

@end

