/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@interface BREvent : NSObject
{
    unsigned short _page;	// 4 = 0x4
    unsigned short _usage;	// 6 = 0x6
    int _value;	// 8 = 0x8
    BOOL _retrigger;	// 12 = 0xc
    double _timeStamp;	// 16 = 0x10
}

- (id)initWithPage:(unsigned short)fp8 usage:(unsigned short)fp12 value:(int)fp16;
- (id)initWithPage:(unsigned short)fp8 usage:(unsigned short)fp12 value:(int)fp16 atTime:(double)fp20;
- (id)description;
- (BOOL)isEqual:(id)fp8;
- (unsigned int)pageUsageHash;
- (unsigned short)page;
- (unsigned short)usage;
- (int)value;
- (BOOL)retriggerEvent;
- (void)makeRetriggerEvent;
- (double)timeStamp;

@end

