/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class BREvent, NSMutableArray, NSTimer;

@interface BREventManager : NSObject
{
    NSObject *_firstResponder;	// 4 = 0x4
    BREvent *_currentEvent;	// 8 = 0x8
    NSTimer *_retriggerTimer;	// 12 = 0xc
    NSTimer *_blockingTimer;	// 16 = 0x10
    NSMutableArray *_eventQueue;	// 20 = 0x14
    struct __CFRunLoopSource *_source;	// 24 = 0x18
    struct __CFRunLoop *_runLoop;	// 28 = 0x1c
    unsigned int _dumpWhenUnblocked:1;	// 32 = 0x20
    unsigned int _eventsBlocked:1;	// 32 = 0x20
    unsigned int _handlingEvent:1;	// 32 = 0x20
    double _flushBeforeTimeStamp;	// 36 = 0x24
}

+ (id)sharedManager;
- (id)init;
- (void)dealloc;
- (void)setFirstResponder:(id)fp8;
- (id)firstResponder;
- (void)blockEventsForTime:(double)fp8 dumpWhenFinished:(BOOL)fp16;
- (id)currentEvent;
- (void)postEvent:(id)fp8;
- (void)dispatchEventOnEventThread:(id)fp8;
- (void)emptyQueue;
- (void)retriggerCurrentEvent;
- (void)retriggerCurrentEventAfterDelay:(double)fp8;
- (void)cancelRetriggerCurrentEvent;

@end

