/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRLayerController.h>

@class BRBlackFadeoutLayer, BRQuadLayer;

@interface BRFullscreenController : BRLayerController
{
    BRBlackFadeoutLayer *_fade;	// 24 = 0x18
    BRQuadLayer *_background;	// 28 = 0x1c
}

- (void)dealloc;
- (void)willBePushed;
- (void)wasPushed;
- (void)willBePopped;
- (void)wasPopped;
- (id)exhumeAnimationWithPoppingController:(id)fp8;
- (id)buryAnimationWithPushingController:(id)fp8;
- (id)popAnimation;
- (id)pushAnimation;

@end

