/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderer.h>

@class BRRenderContext, BRRenderScene;

@interface BRFullscreenRenderer : BRRenderer
{
    BRRenderScene *_scene;	// 4 = 0x4
    BRRenderContext *_context;	// 8 = 0x8
    unsigned int _orderedIn:1;	// 12 = 0xc
}

- (id)init;
- (void)dealloc;
- (id)scene;
- (void)orderOut;
- (void)orderIn;
- (void)displayOnline;
- (void)displayOffline;
- (void)displayCanvasChanged;

@end

