/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class BRRenderLayer;

@interface BRGlyphCellContents : NSObject
{
    int _glyphType;	// 4 = 0x4
    BRRenderLayer *_layer;	// 8 = 0x8
}

- (id)initWithLayer:(id)fp8 glyphType:(int)fp12;
- (void)dealloc;
- (id)layer;
- (int)glyphType;

@end

