/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRImageControl, BRRenderLayer, BRTextControl;

@interface BRGoBackControl : BRControl
{
    BRRenderLayer *_layer;	// 8 = 0x8
    BRTextControl *_text;	// 12 = 0xc
    BRImageControl *_arrow;	// 16 = 0x10
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (id)layer;

@end

