/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRImageLayer, BRRenderLayer, BRTextLayer;

@interface BRHeaderControl : BRControl
{
    BRRenderLayer *_layer;	// 8 = 0x8
    BRTextLayer *_title;	// 12 = 0xc
    BRImageLayer *_icon;	// 16 = 0x10
    float _iconHorizontalOffset;	// 20 = 0x14
    float _iconKerningFactor;	// 24 = 0x18
    unsigned int _keepIconSpace:1;	// 28 = 0x1c
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (id)layer;
- (void)setFrame:(struct _NSRect)fp8;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setIcon:(id)fp8 horizontalOffset:(float)fp12 kerningFactor:(float)fp16;

@end

