/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderLayer.h>

@class BRImageLayer;

@interface BRHorizontalSegmentedWidget : BRRenderLayer
{
    BRImageLayer *_leftEndLayer;	// 56 = 0x38
    BRImageLayer *_centerLayer;	// 60 = 0x3c
    BRImageLayer *_rightEndLayer;	// 64 = 0x40
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)setFrame:(struct _NSRect)fp8;
- (void)setLeftFile:(id)fp8 centerFile:(id)fp12 rightFile:(id)fp16;
- (void)setLeftImage:(id)fp8 centerImage:(id)fp12 rightImage:(id)fp16;

@end

