/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRLayerController.h>

#import "BRMediaPreviewControllerProtocol.h"

@class BRImageControl, BRPanel, BRTextControl;

@interface BRIconPreviewController : BRLayerController <BRMediaPreviewController>
{
    BRLayerController *_controller;	// 24 = 0x18
    BRPanel *_panel;	// 28 = 0x1c
    BRTextControl *_message;	// 32 = 0x20
    BRTextControl *_instruction;	// 36 = 0x24
    BRImageControl *_image;	// 40 = 0x28
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)setMessage:(id)fp8;
- (void)setTexture:(id)fp8;
- (void)setInstructions:(id)fp8;
- (id)layer;
- (void)activate;
- (void)willLoseFocus;
- (void)willRegainFocus;
- (void)willDeactivate;
- (void)deactivate;
- (BOOL)fadeLayerIn;

@end

