/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSDate, NSString, NSURL;

@interface BRImageLoadJob : NSObject
{
    NSString *_imageName;	// 4 = 0x4
    NSURL *_url;	// 8 = 0x8
    BOOL _encrypted;	// 12 = 0xc
    NSDate *_requestDate;	// 16 = 0x10
}

- (id)initWithName:(id)fp8 url:(id)fp12 encrypted:(BOOL)fp16;
- (void)dealloc;
- (id)name;
- (id)url;
- (BOOL)encrypted;
- (id)requestDate;

@end

