/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRLayerController.h>

#import "BRMediaPreviewControllerProtocol.h"

@class BRImageControl, BRPanel, BRSyncProgressControl;

@interface BRImageAndSyncingPreviewController : BRLayerController <BRMediaPreviewController>
{
    BRPanel *_panel;	// 24 = 0x18
    BRImageControl *_imageControl;	// 28 = 0x1c
    BRSyncProgressControl *_syncProgressControl;	// 32 = 0x20
    BOOL _hasProgress;	// 36 = 0x24
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)setTexture:(id)fp8;
- (void)setImage:(struct CGImage *)fp8 downsampleTo:(struct _NSSize)fp12;
- (void)setImage:(struct CGImage *)fp8;
- (id)layer;
- (id)imageControl;
- (void)activate;
- (void)willLoseFocus;
- (void)willRegainFocus;
- (void)willDeactivate;
- (void)deactivate;
- (BOOL)fadeLayerIn;
- (void)setHasSyncProgress:(BOOL)fp8;

@end

