/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@class NSConditionLock, NSLock, NSMutableArray, NSMutableDictionary, NSString;

@interface BRImageManager : BRSingleton
{
    unsigned long long _maxCacheSize;	// 4 = 0x4
    NSConditionLock *_writeLock;	// 12 = 0xc
    NSConditionLock *_maintLock;	// 16 = 0x10
    unsigned long long _cacheSize;	// 20 = 0x14
    NSString *_imageCachePath;	// 28 = 0x1c
    NSMutableDictionary *_images;	// 32 = 0x20
    NSMutableDictionary *_remoteImageRequests;	// 36 = 0x24
    NSLock *_remoteImageLock;	// 40 = 0x28
    NSMutableArray *_jobQueue;	// 44 = 0x2c
    BOOL _processJobs;	// 48 = 0x30
}

+ (id)singleton;
+ (void)setSingleton:(id)fp8;
- (id)init;
- (void)dealloc;
- (BOOL)isImageAvailable:(id)fp8;
- (id)imageNameFromURL:(id)fp8;
- (id)writeImageFromURL:(id)fp8;
- (id)writeEncryptedImageFromURL:(id)fp8;
- (id)writeImageFromURL:(id)fp8 isEncrypted:(BOOL)fp12;
- (void)writeImage:(struct CGImage *)fp8 named:(id)fp12;
- (void)_writeImageData:(id)fp8 named:(id)fp12;
- (struct CGImage *)imageNamed:(id)fp8;
- (void)removeImageNamed:(id)fp8;
- (void)remoteImageRequestForMediaID:(id)fp8;
- (void)receivedRemoteImage:(struct CGImage *)fp8 forID:(id)fp12;
- (BOOL)hasRemoteImageBeenRequestedForMediaID:(id)fp8;
- (void)purgeRemoteRequest;

@end

