/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRTextMenuItemLayer.h>

@class BRImageLayer;

@interface BRImageItemMenuLayer : BRTextMenuItemLayer
{
    BRImageLayer *_imageItem;	// 108 = 0x6c
}

+ (id)imageMenuItemWithTexture:(id)fp8 andScene:(id)fp12;
- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)setFrame:(struct _NSRect)fp8;

@end

