/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRIPv4AddressSelectionLayer.h>

@interface BRIPv4AddressSelectionLayer (Framing)
- (float)_layoutUIWithHeight:(float)fp8;
- (struct _NSRect)_selectionWidgetFrameForSelection:(int)fp8;
- (struct _NSRect)_arrowsFrameForSelection:(int)fp8;
- (struct _NSRect)_digitFrameForSelection:(int)fp8;
- (struct _NSRect)_cellFrameForSelection:(int)fp8;
- (float)_singleCellWidth;
@end

