/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

#import "BRTextContainerProtocol.h"

@class BRIPv4AddressSelectionLayer, BRRenderLayer, BRTextLayer;

@interface BRIPv4AddressEntryControl : BRControl <BRTextContainer>
{
    BRRenderLayer *_masterLayer;	// 8 = 0x8
    BRIPv4AddressSelectionLayer *_addressPicker;	// 12 = 0xc
    BRTextLayer *_labelLayer;	// 16 = 0x10
    struct _NSSize _addressPickerSize;	// 20 = 0x14
    float _labelPadding;	// 28 = 0x1c
    id _textEntryDelegate;	// 32 = 0x20
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (struct _NSSize)preferredSizeFromScreenSize:(struct _NSSize)fp8;
- (void)setDelegate:(id)fp8;
- (void)setLabel:(id)fp8;
- (void)reset;
- (void)setFrame:(struct _NSRect)fp8;
- (id)layer;
- (BOOL)brEventAction:(id)fp8;
- (id)stringValue;

@end

