/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderLayer.h>

@class BRIPv4AddressSelectionWidget, BRImageLayer, BRTextLayer, NSArray;

@interface BRIPv4AddressSelectionLayer : BRRenderLayer
{
    NSArray *_octetBackgroundLayers;	// 56 = 0x38
    NSArray *_digitLayers;	// 60 = 0x3c
    NSArray *_dotLayers;	// 64 = 0x40
    BRImageLayer *_arrowsLayer;	// 68 = 0x44
    BRIPv4AddressSelectionWidget *_selectionWidget;	// 72 = 0x48
    BRTextLayer *_doneLayer;	// 76 = 0x4c
    int _selection;	// 80 = 0x50
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (struct _NSRect)preferredFrameForScreenSize:(struct _NSSize)fp8;
- (BOOL)moveSelectionRight;
- (BOOL)moveSelectionLeft;
- (BOOL)incrementSelection;
- (BOOL)decrementSelection;
- (id)ipAddress;
- (BOOL)doneButtonSelected;
- (void)reset;
- (void)setFrame:(struct _NSRect)fp8;

@end

