/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRBaseMediaProvider.h>

@interface BRIPhotoMediaProvider : BRBaseMediaProvider
{
}

- (id)mediaTypes;
- (id)photoConnection;
- (id)mediaAssetWithID:(id)fp8;

@end

