/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRBaseMediaCollection.h>

@class NSDictionary, NSMutableArray;

@interface BRIPhotoMediaCollection : BRBaseMediaCollection
{
    NSDictionary *_dictionary;	// 8 = 0x8
    BRIPhotoMediaCollection *_parent;	// 12 = 0xc
    NSMutableArray *_children;	// 16 = 0x10
}

+ (id)mediaCollectionFromMediaProvider:(id)fp8 withDictionary:(id)fp12;
- (id)initWithProvider:(id)fp8 dictionary:(id)fp12;
- (void)dealloc;
- (id)description;
- (id)title;
- (id)collectionID;
- (void)setParentCollection:(id)fp8;
- (void)addChildCollection:(id)fp8;
- (id)collectionType;
- (id)childCollections;
- (id)parentCollection;
- (BOOL)hasCoverArt;
- (struct CGImage *)coverArt;
- (id)mediaAssets;
- (id)collectionDictionary;
- (BOOL)isLocal;

@end

