/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRBaseMediaAsset.h>

@class NSString;

@interface BRIPhotoMediaAsset : BRBaseMediaAsset
{
    NSString *_assetID;	// 8 = 0x8
}

+ (id)mediaAssetFromMediaProvider:(id)fp8 withAssetID:(id)fp12;
- (id)initFromMediaProvider:(id)fp8 withAssetID:(id)fp12;
- (void)dealloc;
- (id)description;
- (id)assetID;
- (unsigned int)imageID;
- (BOOL)hasCoverArt;
- (struct CGImage *)coverArt;
- (id)title;
- (id)mediaType;
- (BOOL)isLocal;

@end

