/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@interface BRITunesLibraryPrefsAccess : BRSingleton
{
    id _prefsDelegate;	// 4 = 0x4
}

+ (id)singleton;
+ (void)setSingleton:(id)fp8;
- (void)dealloc;
- (void)setITunesPrefsDelegate:(id)fp8;
- (BOOL)musicPlaybackUsesSoundCheck;
- (void)setMusicPlaybackUsesSoundCheck:(BOOL)fp8;

@end

