/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import "BREventResponderProtocol.h"

@class BRControllerStack, BRRenderLayer, BRRenderScene, NSArray, NSMutableDictionary;

@interface BRLayerController : NSObject <BREventResponder>
{
    NSMutableDictionary *_labels;	// 4 = 0x4
    NSArray *_controls;	// 8 = 0x8
    BRControllerStack *_stack;	// 12 = 0xc
    BRRenderScene *_scene;	// 16 = 0x10
    BRRenderLayer *_master;	// 20 = 0x14
}

+ (id)layerControllerWithScene:(id)fp8;
- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (id)scene;
- (id)masterLayer;
- (struct _NSRect)masterLayerFrame;
- (void)resetLayout;
- (void)setControls:(id)fp8;
- (void)addControl:(id)fp8;
- (id)controls;
- (void)setStack:(id)fp8;
- (id)stack;
- (BOOL)firstResponder;
- (void)willBePushed;
- (void)wasPushed;
- (void)willBePopped;
- (void)wasPopped;
- (void)willBeBuried;
- (void)wasBuriedByPushingController:(id)fp8;
- (void)willBeExhumed;
- (void)wasExhumedByPoppingController:(id)fp8;
- (BOOL)brEventAction:(id)fp8;
- (id)popAnimation;
- (id)pushAnimation;
- (id)exhumeAnimationWithPoppingController:(id)fp8;
- (id)buryAnimationWithPushingController:(id)fp8;
- (void)addLabel:(id)fp8;
- (void)removeLabel:(id)fp8;
- (BOOL)isLabelled:(id)fp8;
- (BOOL)isNetworkDependent;
- (BOOL)popsOnBury;

@end

