/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRCenteredMenuController.h>

#import "BRMenuListItemProviderProtocol.h"

@class BRSystemLanguages, NSArray, NSDictionary;

@interface BRLanguageChooserController : BRCenteredMenuController <BRMenuListItemProvider>
{
    BRSystemLanguages *_systemLanguages;	// 136 = 0x88
    NSArray *_languageKeys;	// 140 = 0x8c
    NSDictionary *_languageKeysAndPrompts;	// 144 = 0x90
    id _delegate;	// 148 = 0x94
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)itemSelected:(long)fp8;
- (id)itemForRow:(long)fp8;
- (long)itemCount;
- (id)titleForRow:(long)fp8;
- (long)rowForTitle:(id)fp8;
- (void)setSelectionDelegate:(id)fp8;
- (long)defaultIndex;
- (float)computeMenuWidth;

@end

