/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderLayer.h>

@class BRDividerLayer, NSArray, NSDictionary, NSMutableDictionary;

@interface BRListLayer : BRRenderLayer
{
    NSMutableDictionary *_dividerLayers;	// 56 = 0x38
    NSDictionary *_dividers;	// 60 = 0x3c
    NSArray *_rows;	// 64 = 0x40
    BRDividerLayer *_dividerLayer;	// 68 = 0x44
    float _rowHeight;	// 72 = 0x48
    float _translation;	// 76 = 0x4c
    float _dividerIndex;	// 80 = 0x50
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (BOOL)clipsToFrame;
- (void)setRowHeight:(float)fp8;
- (float)rowHeight;
- (void)setRows:(id)fp8;
- (id)rows;
- (void)setScrollTranslate:(float)fp8;
- (float)scrollTranslate;
- (void)removeDividerLayerForKey:(id)fp8;
- (void)setDividers:(id)fp8;

@end

