/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRListControl.h>

@interface BRListControl (Notifications)
- (void)_sendNotificationNamed:(id)fp8;
- (void)_listFrameChanged:(id)fp8;
- (void)_languageChanged:(id)fp8;
@end

