/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class BRTextMenuItemLayer;

@interface BRMainMenuSyncSpinnerItem : NSObject
{
    BRTextMenuItemLayer *_itemLayer;	// 4 = 0x4
    long _row;	// 8 = 0x8
}

- (id)initWithItemLayer:(id)fp8 row:(long)fp12;
- (void)dealloc;
- (id)itemLayer;
- (long)row;

@end

