/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMenuController.h>

@class BRBlurryImageLayer, BRMainMenuSyncSpinnerItem, BRMarchingIconLayer, BRMediaType, BRMusicPlayer, NSArray, NSString;

@interface BRMainMenuController : BRMenuController
{
    NSArray *_applianceInfo;	// 64 = 0x40
    NSArray *_activeAppliances;	// 68 = 0x44
    BRMarchingIconLayer *_iconMarch;	// 72 = 0x48
    BRBlurryImageLayer *_frontIcon;	// 76 = 0x4c
    NSString *_deviceName;	// 80 = 0x50
    BRMusicPlayer *_player;	// 84 = 0x54
    BRMediaType *_fileCopyTypeInProgress;	// 88 = 0x58
    BRMainMenuSyncSpinnerItem *_currentSpinningMenuLayer;	// 92 = 0x5c
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)resetLayout;
- (id)deviceName;
- (struct _NSRect)listFrameForBounds:(struct _NSSize)fp8;
- (BOOL)brEventAction:(id)fp8;
- (void)willBePushed;
- (void)wasPopped;
- (void)willBeBuried;
- (void)wasBuriedByPushingController:(id)fp8;
- (void)willBeExhumed;
- (void)wasExhumedByPoppingController:(id)fp8;
- (id)buryAnimationWithPushingController:(id)fp8;
- (id)exhumeAnimationWithPoppingController:(id)fp8;
- (void)itemSelected:(long)fp8;
- (float)listIconYFactor;

@end

