/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRAnimation.h>

@interface BRMainMenuTransitionAnimation : BRAnimation
{
    BRAnimation *_outgoingAnimation;	// 60 = 0x3c
}

- (void)dealloc;
- (void)setOutgoingMenuAnimation:(id)fp8;
- (void)positionChanged:(float)fp8;

@end

