/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMainMenuController.h>

@interface BRMainMenuController (ApplianceLoading)
- (void)_loadAppliances:(BOOL)fp8;
- (void)_resetActiveAppliances;
- (void)_updateActiveApplianceList;
@end

