/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderLayer.h>

@class BRTextLayer;

@interface BRMetadataLineLayer : BRRenderLayer
{
    BRTextLayer *_labelLayer;	// 56 = 0x38
    BRTextLayer *_valueLayer;	// 60 = 0x3c
    float _maxLabelWidth;	// 64 = 0x40
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)setLabel:(id)fp8;
- (void)setValue:(id)fp8;
- (id)label;
- (id)value;
- (void)setMaxLabelWidth:(float)fp8;
- (void)setFrame:(struct _NSRect)fp8;

@end

