/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMediaParadeLayer.h>

@interface BRMediaParadeLayer (ImageSizing)
- (struct _NSRect)_maxImageRect;
- (struct _NSRect)_rectForImage:(id)fp8 withMaxRect:(struct _NSRect)fp12;
@end

