/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMediaMenuController.h>

@interface BRMediaMenuController (PreviewManagement)
- (void)_updatePreview;
- (void)_removeAllPreviews;
- (id)_handleSimplePreviewAdd:(id)fp8;
- (id)_handlePreviewSwap:(id)fp8;
- (id)_handleSwapInProgress:(id)fp8;
- (void)_swapAnimationComplete:(id)fp8;
- (void)_waitUntilPreviewCrossfadeComplete;
@end

