/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderLayer.h>

@class BRListLayer, BRSelectionLozengeLayer, NSMutableDictionary;

@interface BRMenuListLayer : BRRenderLayer
{
    id _source;	// 56 = 0x38
    NSMutableDictionary *_dividers;	// 60 = 0x3c
    long _rowCount;	// 64 = 0x40
    long _maxVisibleRows;	// 68 = 0x44
    struct _NSRange _visibleRange;	// 72 = 0x48
    long _selection;	// 80 = 0x50
    double _remainder;	// 84 = 0x54
    double _widgetOverheightFactor;	// 92 = 0x5c
    BRListLayer *_list;	// 100 = 0x64
    BRSelectionLozengeLayer *_widget;	// 104 = 0x68
    unsigned int _neededScrollingPreviously:1;	// 108 = 0x6c
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)setFrame:(struct _NSRect)fp8;
- (void)setDatasource:(id)fp8;
- (id)datasource;
- (void)reload;
- (long)maximumVisibleItemsForListHeight:(float)fp8;
- (float)minimumRowHeightForVisibleItems:(long)fp8;
- (float)extraWidgetSpace;
- (long)maxVisibleRows;
- (id)visibleRows;
- (void)setRowHeight:(float)fp8;
- (float)rowHeight;
- (id)selectedRowObject;
- (id)waitSpinner;
- (long)itemCount;
- (void)setSelection:(double)fp8;
- (double)selection;
- (void)setDividerIndex:(long)fp8;
- (void)addDividerAtIndex:(long)fp8;
- (void)removeDividerAtIndex:(long)fp8;
- (long)currentWidgetIndex;
- (struct _NSRect)textFrame;

@end

