/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BROptionDialog.h>

@class BRMediaHost;

@interface BRMediaHostDisconnectedDialog : BROptionDialog
{
    BRMediaHost *_mediaHost;	// 164 = 0xa4
    unsigned int _timerSatisfied:1;	// 168 = 0xa8
}

- (id)initWithScene:(id)fp8 host:(id)fp12;
- (void)dealloc;
- (void)goToSources;
- (void)setMediaHost:(id)fp8;
- (id)mediaHost;
- (void)willBePushed;

@end

