/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@interface BRMediaPlayer : NSObject
{
    id _media;	// 4 = 0x4
}

- (void)dealloc;
- (int)playerState;
- (BOOL)setMedia:(id)fp8 error:(id *)fp12;
- (id)media;
- (float)elapsedPlaybackTime;
- (void)setElapsedPlaybackTime:(float)fp8;
- (double)trackDuration;
- (float)bufferingProgress;
- (id)currentChapterTitle;
- (void)setMuted:(BOOL)fp8;
- (BOOL)interruptsSyncingWhenPlaying;
- (BOOL)muted;
- (BOOL)initiatePlayback:(id *)fp8;
- (void)play;
- (void)pause;
- (void)stop;
- (void)pressAndHoldLeftArrow;
- (void)pressAndHoldRightArrow;
- (void)resume;
- (void)leftArrowClick;
- (void)rightArrowClick;

@end

