/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRLayerController.h>

#import "BRApplianceControllerIconProtocolProtocol.h"

@class BRImageLayer, BRListControl, BRTextLayer, NSArray;

@interface BRMenuController : BRLayerController <BRApplianceControllerIconProtocol>
{
    BRListControl *_listControl;	// 24 = 0x18
    BRImageLayer *_listIcon;	// 28 = 0x1c
    float _listIconHorizontalOffset;	// 32 = 0x20
    float _listIconKerningFactor;	// 36 = 0x24
    unsigned int _keepIconSpace:1;	// 40 = 0x28
    NSArray *_menuPath;	// 44 = 0x2c
    unsigned int _preSelectedIndexCalculated:1;	// 48 = 0x30
    NSArray *_dataSet;	// 52 = 0x34
    id _selectedObject;	// 56 = 0x38
    BRTextLayer *_listTitle;	// 60 = 0x3c
}

+ (struct _NSRect)listFrameForBounds:(struct _NSSize)fp8;
- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)resetLayout;
- (id)list;
- (void)setListTitle:(id)fp8;
- (id)listTitle;
- (void)setListIcon:(id)fp8;
- (id)listIcon;
- (void)setListIconHorizontalOffset:(float)fp8;
- (float)listIconHorizontalOffset;
- (void)setListIconKerningFactor:(float)fp8;
- (float)listIconKerningFactor;
- (void)setListIcon:(id)fp8 horizontalOffset:(float)fp12 kerningFactor:(float)fp16;
- (struct _NSRect)listFrameForBounds:(struct _NSSize)fp8;
- (void)frameForTitleIcon:(struct _NSRect *)fp8 andText:(struct _NSRect *)fp12 forBounds:(struct _NSSize)fp16;
- (void)itemSelected:(long)fp8;
- (int)soundForSelectingItem:(long)fp8;
- (BOOL)indexForPreviousSelection:(long *)fp8;
- (void)setPreSelectedIndex;
- (long)defaultIndex;
- (float)listIconYFactor;
- (void)setApplianceIcon:(id)fp8;
- (void)setApplianceIconHidden:(BOOL)fp8;
- (struct _NSRect)applianceIconFrame;
- (void)willBePushed;
- (void)willBeBuried;
- (void)willBeExhumed;
- (void)willBePopped;
- (void)setSelectedObject:(id)fp8;
- (id)selectedObject;
- (BOOL)isVolatile;
- (id)loadModelData;
- (void)refreshControllerForModelUpdate;
- (BOOL)isCurrentSelectionValidForModelData:(id)fp8;
- (BOOL)shouldRefreshForUpdateToObject:(id)fp8;

@end

