/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import "BRMediaPreviewControllerProtocol.h"

@class BRAnimation, BRImageLayer, BRMetadataLayer, BRRenderLayer, BRRenderScene, NSTimer;

@interface BRMetadataPreviewController : NSObject <BRMediaPreviewController>
{
    id _asset;	// 4 = 0x4
    BRRenderScene *_scene;	// 8 = 0x8
    BRRenderLayer *_mainLayer;	// 12 = 0xc
    BRImageLayer *_coverArtLayer;	// 16 = 0x10
    BRMetadataLayer *_metadataLayer;	// 20 = 0x14
    BRAnimation *_animation;	// 24 = 0x18
    struct _NSRect _frame;	// 28 = 0x1c
    int _state;	// 44 = 0x2c
    NSTimer *_timer;	// 48 = 0x30
    unsigned int _blockDuringAnimation:1;	// 52 = 0x34
    unsigned int _artworkNeedsUpdating:1;	// 52 = 0x34
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)setAsset:(id)fp8;
- (void)setShowsMetadataImmediately:(BOOL)fp8;
- (BOOL)showsMetadataImmediately;
- (void)setBlocksDuringAnimation:(BOOL)fp8;
- (id)layer;
- (void)activate;
- (void)willLoseFocus;
- (void)willRegainFocus;
- (void)willDeactivate;
- (void)deactivate;
- (BOOL)fadeLayerIn;

@end

