/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMenuListLayer.h>

@interface BRMenuListLayer (VisibleRowList)
- (void)_resetRowPositions:(double)fp8;
- (void)_updateListDataForSelectedRow:(long)fp8;
- (struct _NSRange)_getVisibleRangeForIndex:(long)fp8;
- (BOOL)_listNeedsScrolling:(double)fp8;
- (double)_selectionRectIndexForRow:(double)fp8;
- (void)checkForItemsAbove:(char *)fp8 andBelow:(char *)fp12;
@end

