/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMetadataLayer.h>

@interface BRMetadataLayer (Framing)
- (void)_updateFrame;
- (void)_calculateTitleLineHeight;
- (void)_calculateSummaryLineHeight;
@end

