/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@interface BRMetadataPopulatorFactory : BRSingleton
{
    id _tvShowPopulator;	// 4 = 0x4
    id _podcastPopulator;	// 8 = 0x8
    id _musicVideoPopulator;	// 12 = 0xc
    id _songPopulator;	// 16 = 0x10
    id _moviePopulator;	// 20 = 0x14
    id _movieTrailerPopulator;	// 24 = 0x18
    id _rssPopulator;	// 28 = 0x1c
    id _audiobookPopulator;	// 32 = 0x20
    id _musicAlbumPopulator;	// 36 = 0x24
}

+ (id)singleton;
+ (void)setSingleton:(id)fp8;
- (void)dealloc;
- (id)populatorForAsset:(id)fp8;

@end

