/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@interface BRMediaPreviewControllerFactory : NSObject
{
}

+ (id)previewControllerForAsset:(id)fp8 withDelegate:(id)fp12 scene:(id)fp16;
+ (id)previewControllerForAssets:(id)fp8 withDelegate:(id)fp12 scene:(id)fp16;

@end

