/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMenuController.h>

#import "BRMediaPreviewFactoryDelegateProtocol.h"

@class BRAnimation, BRRenderLayer, NSMutableArray, NSTimer;

@interface BRMediaMenuController : BRMenuController <BRMediaPreviewFactoryDelegate>
{
    long _previewState;	// 64 = 0x40
    BRAnimation *_previewFader;	// 68 = 0x44
    id _previewController;	// 72 = 0x48
    BRRenderLayer *_previewLayer;	// 76 = 0x4c
    id _outgoingController;	// 80 = 0x50
    BRRenderLayer *_outgoingLayer;	// 84 = 0x54
    float _previewDelay;	// 88 = 0x58
    NSTimer *_previewDelayTimer;	// 92 = 0x5c
    NSMutableArray *_musicStoreCollections;	// 96 = 0x60
    NSTimer *_musicStoreTimer;	// 100 = 0x64
    unsigned int _musicStoreSelected:1;	// 104 = 0x68
    unsigned int _musicStorePreviewRequested:1;	// 104 = 0x68
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (id)previewControllerForItem:(long)fp8;
- (void)updatePreviewController;
- (struct _NSRect)previewFrameForBounds:(struct _NSSize)fp8;
- (void)wasPushed;
- (void)willBePopped;
- (void)wasPopped;
- (void)willBeBuried;
- (void)wasBuriedByPushingController:(id)fp8;
- (void)willBeExhumed;
- (void)wasExhumedByPoppingController:(id)fp8;
- (id)mediaPreviewMissingMediaType;
- (BOOL)mediaPreviewShouldShowMetadata;
- (BOOL)mediaPreviewShouldShowMetadataImmediately;
- (void)refreshControllerForModelUpdate;

@end

