/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class BRAdornedMenuItemLayer;

@interface BRMenuItemMediator : NSObject
{
    BRAdornedMenuItemLayer *_menuItem;	// 4 = 0x4
    SEL _mediaParadeSelector;	// 8 = 0x8
    SEL _menuSelector;	// 12 = 0xc
}

- (id)initWithMenuItem:(id)fp8;
- (void)dealloc;
- (id)menuItem;
- (void)setMediaPreviewSelector:(SEL)fp8;
- (SEL)mediaPreviewSelector;
- (void)setMenuActionSelector:(SEL)fp8;
- (SEL)menuActionSelector;

@end

