/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRAssetArtLoader.h>

@class BRRenderScene;

@interface BRMediaParadeProvider : BRAssetArtLoader
{
    BRRenderScene *_scene;	// 60 = 0x3c
}

- (id)initWithScene:(id)fp8;
- (id)finalFormForImage:(struct CGImage *)fp8;

@end

