/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMetadataPreviewController.h>

@interface BRMetadataPreviewController (Private)
- (void)_activate;
- (void)_metadataTimerHandler:(id)fp8;
- (void)_showMetadataWithAnimation:(BOOL)fp8;
- (void)_loadCoverArt;
- (void)_updateCoverArt:(id)fp8;
- (id)_prepareArtAnimation;
- (id)_prepareMetadataAnimation;
- (void)_populateMetadata;
- (void)_layoutMetadata;
- (float)_reflectionAmountForArtWithMetadata;
- (BOOL)_assetHasMetadata;
- (void)_cleanupTimer;
- (void)_metadataTransitionCompleteHandler:(id)fp8;
- (struct CGImage *)_imageFromAsset:(id)fp8 showDefaultCoverArt:(BOOL)fp12;
- (void)_configureLargeCoverArt;
- (void)_configureSmallCoverArt;
@end

