/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMenuListLayer.h>

@interface BRMenuListLayer (Private)
- (id)_dividers;
- (id)_dividersInRange:(struct _NSRange)fp8 forDisplayRange:(struct _NSRange)fp16;
@end

