/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderLayer.h>

@class BRDividerLayer, BRImageLayer, BRMetadataLinesLayer, BRTextLayer, NSArray;

@interface BRMetadataLayer : BRRenderLayer
{
    BRTextLayer *_titleLayer;	// 56 = 0x38
    BRImageLayer *_ratingImageLayer;	// 60 = 0x3c
    BRTextLayer *_summaryLayer;	// 64 = 0x40
    BRMetadataLinesLayer *_metadataLinesLayer;	// 68 = 0x44
    BRTextLayer *_copyrightLayer;	// 72 = 0x48
    BRDividerLayer *_topDividerLayer;	// 76 = 0x4c
    BRDividerLayer *_middleDividerLayer;	// 80 = 0x50
    BRDividerLayer *_bottomDividerLayer;	// 84 = 0x54
    NSArray *_metadataObjs;	// 88 = 0x58
    NSArray *_metadataLabels;	// 92 = 0x5c
    float _frameWidth;	// 96 = 0x60
    float _maxHeight;	// 100 = 0x64
    float _titleLineHeight;	// 104 = 0x68
    float _summaryLineHeight;	// 108 = 0x6c
    float _topDividerHeight;	// 112 = 0x70
    float _middleDividerHeight;	// 116 = 0x74
    float _bottomDividerHeight;	// 120 = 0x78
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)resetAllFields;
- (void)setTitle:(id)fp8;
- (void)setRating:(id)fp8;
- (void)setSummary:(id)fp8;
- (void)setMetadata:(id)fp8 withLabels:(id)fp12;
- (void)setCopyright:(id)fp8;
- (void)setWidth:(float)fp8;
- (void)setMaxHeight:(float)fp8;
- (void)setOrigin:(struct _NSPoint)fp8;
- (void)setFrame:(struct _NSRect)fp8;

@end

