/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import "BRMediaPreviewControllerProtocol.h"

@class BRMediaParadeLayer, BRMediaParadeProvider;

@interface BRMediaParadeController : NSObject <BRMediaPreviewController>
{
    BRMediaParadeLayer *_layer;	// 4 = 0x4
    BRMediaParadeProvider *_provider;	// 8 = 0x8
    double _timeFreq;	// 12 = 0xc
    double _prevTime;	// 20 = 0x14
    unsigned int _waitingForQueue:1;	// 28 = 0x1c
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (id)layer;
- (void)activate;
- (void)willRegainFocus;
- (void)willLoseFocus;
- (void)willDeactivate;
- (void)deactivate;
- (BOOL)fadeLayerIn;
- (void)setAssets:(id)fp8;

@end

