/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMiniTransportLayer.h>

@interface BRMiniTransportLayer (Private)
- (void)_createSublayersInScene:(id)fp8;
- (void)_updateFrames;
@end

