/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderLayer.h>

@class BRTextLayer, NSDictionary;

@interface BRMiniTransportLayer : BRRenderLayer
{
    int _currentState;	// 56 = 0x38
    BRTextLayer *_progressText;	// 60 = 0x3c
    BRTextLayer *_durationText;	// 64 = 0x40
    NSDictionary *_attributes;	// 68 = 0x44
    struct _NSRect _barFrame;	// 72 = 0x48
    float _percentPlayed;	// 88 = 0x58
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)setFrame:(struct _NSRect)fp8;
- (void)renderLayer;
- (void)setState:(int)fp8 progressString:(id)fp12 durationString:(id)fp16 percentComplete:(float)fp20;

@end

