/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMusicKeyFilterTracklistMenuController.h>

#import "BRMenuListItemProviderProtocol.h"

@interface BRMusicKeyFilterTracklistMenuController (MenuItemProvider) <BRMenuListItemProvider>
- (id)itemForRow:(long)fp8;
- (long)itemCount;
- (id)titleForRow:(long)fp8;
- (long)rowForTitle:(id)fp8;
@end

