/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMediaMenuController.h>

@class NSArray, NSMutableDictionary, NSPredicate, NSString;

@interface BRMusicKeyFilterTracklistMenuController : BRMediaMenuController
{
    id _selectionDelegate;	// 108 = 0x6c
    NSString *_key;	// 112 = 0x70
    NSArray *_tracks;	// 116 = 0x74
    NSArray *_values;	// 120 = 0x78
    unsigned int _allowAllTracks:1;	// 124 = 0x7c
    unsigned int _ignorePrefixes:1;	// 124 = 0x7c
    unsigned int _allowShuffle:1;	// 124 = 0x7c
    unsigned int _showMetadata:1;	// 124 = 0x7c
    NSPredicate *_predicate;	// 128 = 0x80
    NSMutableDictionary *_menuItemCollections;	// 132 = 0x84
}

+ (id)menuControllerWithPredicate:(id)fp8 keyFilter:(id)fp12 ignoringPrefixes:(BOOL)fp16 withScene:(id)fp20;
- (id)initWithPredicate:(id)fp8 keyFilter:(id)fp12 ignoringPrefixes:(BOOL)fp16 withScene:(id)fp20;
- (void)dealloc;
- (BOOL)isVolatile;
- (id)loadModelData;
- (void)refreshControllerForModelUpdate;
- (BOOL)shouldRefreshForUpdateToObject:(id)fp8;
- (void)setSelectionDelegate:(id)fp8;
- (void)setHasShuffleOption:(BOOL)fp8;
- (void)setShowMetadataOption:(BOOL)fp8;
- (void)itemSelected:(long)fp8;
- (id)previewControllerForItem:(long)fp8;
- (BOOL)mediaPreviewShouldShowMetadata;
- (id)mediaPreviewMissingMediaType;

@end

