/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMusicNowPlayingLayer.h>

@class BRQuartzComposerLayer, NSDictionary;

@interface BRMusicQCNowPlayingLayer : BRMusicNowPlayingLayer
{
    BRQuartzComposerLayer *_qcLayer;	// 56 = 0x38
    NSDictionary *_currentTrack;	// 60 = 0x3c
    long _seedValue;	// 64 = 0x40
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)setFrame:(struct _NSRect)fp8;
- (BOOL)setCompositionPath:(id)fp8;
- (void)setCurrentTrackInfo:(id)fp8;
- (void)updateCurrentTrackInfo:(id)fp8;
- (void)setCurrentTrackInfo:(id)fp8 forceUpdate:(BOOL)fp12;
- (id)currentTrackInfo;
- (void)setElapsedTime:(double)fp8;
- (void)setShuffleState:(BOOL)fp8;
- (void)setRepeatMode:(int)fp8;
- (void)setPlayerState:(int)fp8;
- (void)wasActivated;
- (void)wasDeactived;

@end

