/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderLayer.h>

@interface BRMusicNowPlayingLayer : BRRenderLayer
{
}

- (void)setCurrentTrackInfo:(id)fp8;
- (id)currentTrackInfo;
- (void)setElapsedTime:(double)fp8;
- (void)setShuffleState:(BOOL)fp8;
- (void)setRepeatMode:(int)fp8;
- (void)setPlayerState:(int)fp8;
- (void)wasActivated;
- (void)wasDeactived;

@end

