/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

@protocol BRMusicKeyFilterSelectionTarget <NSObject>
- (id)previewAssetsForValue:(id)fp8 ofKey:(id)fp12 forTracks:(id)fp16;
- (void)selectedValue:(id)fp8 forKey:(id)fp12 withPredicate:(id)fp16 allowShuffle:(BOOL)fp20;
- (void)allTracksSelectedWithPredicate:(id)fp8 forKey:(id)fp12 allowShuffle:(BOOL)fp16;
@end

