/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRBaseParserDelegate.h>

@class BRMusicStoreCollection, BRRSSMediaAsset, NSAutoreleasePool;

@interface BRMusicStoreDelegate : BRBaseParserDelegate
{
    id _provider;	// 8 = 0x8
    BRRSSMediaAsset *_mediaAsset;	// 12 = 0xc
    BRMusicStoreCollection *_collection;	// 16 = 0x10
    unsigned int _inCollection:1;	// 20 = 0x14
    NSAutoreleasePool *_pool;	// 24 = 0x18
}

- (id)initWithMediaProvider:(id)fp8 collection:(id)fp12;
- (void)dealloc;
- (void)startEntryWithAttributes:(id)fp8;
- (void)startLinkWithAttributes:(id)fp8;
- (void)startCategoryWithAttributes:(id)fp8;
- (void)startCollectionWithAttributes:(id)fp8;
- (void)endCollection;
- (void)endId;
- (void)endName;
- (void)endArtist;
- (void)endImage;
- (void)endReleaseDate;
- (void)endEntry;
- (void)endRights;
- (void)endSummary;
- (void)endDuration;

@end

