/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMediaMenuController.h>

#import "BRMenuListItemProviderProtocol.h"

@class NSArray, NSPredicate;

@interface BRMusicPlaylistMenuController : BRMediaMenuController <BRMenuListItemProvider>
{
    NSArray *_playlists;	// 108 = 0x6c
    long _priorSelection;	// 112 = 0x70
    NSPredicate *_predicate;	// 116 = 0x74
}

- (id)initWithPredicate:(id)fp8 scene:(id)fp12;
- (void)dealloc;
- (BOOL)isVolatile;
- (id)loadModelData;
- (void)refreshControllerForModelUpdate;
- (BOOL)shouldRefreshForUpdateToObject:(id)fp8;
- (void)itemSelected:(long)fp8;
- (id)previewControllerForItem:(long)fp8;
- (id)mediaPreviewMissingMediaType;
- (id)itemForRow:(long)fp8;
- (long)itemCount;
- (id)titleForRow:(long)fp8;
- (long)rowForTitle:(id)fp8;

@end

