/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMusicCategoryMenuController.h>

@class BRMusicNowPlayingMonitor, BRMusicPlayer, NSArray, NSString;

@interface BRMusicMenuController : BRMusicCategoryMenuController
{
    NSArray *_headerRows;	// 112 = 0x70
    BRMusicPlayer *_player;	// 116 = 0x74
    NSString *_selectedRowTitleBeforeBurial;	// 120 = 0x78
    BRMusicNowPlayingMonitor *_npMonitor;	// 124 = 0x7c
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (id)musicStoreBaseType;
- (long)defaultIndex;
- (void)wasPushed;
- (void)willBePushed;
- (void)wasPopped;
- (void)willBePopped;
- (void)willBeExhumed;
- (void)itemSelected:(long)fp8;

@end

