/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@class BRMusicStoreCollection, NSConditionLock, NSMutableArray;

@interface BRMusicStore : BRSingleton
{
    NSConditionLock *_mediaLoadLock;	// 4 = 0x4
    BRMusicStoreCollection *_rootCollection;	// 8 = 0x8
    NSMutableArray *_mediaLoadJobs;	// 12 = 0xc
    id _provider;	// 16 = 0x10
    BOOL _processJobs;	// 20 = 0x14
    BOOL _initializing;	// 21 = 0x15
}

+ (void)setSingleton:(id)fp8;
+ (id)singleton;
- (id)init;
- (void)dealloc;
- (id)provider;
- (id)musicStoreRootCollection;
- (void)purgeMusicStore;
- (void)loadCollection:(id)fp8;

@end

