/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMusicNowPlayingController.h>

@interface BRMusicNowPlayingController (VisualUpdate)
- (void)_updateEverything;
- (void)_updateStaticValues;
- (void)_updateTrackWithTransition:(BOOL)fp8;
- (void)_updateState;
- (void)_updateElapsedTime;
- (void)_updateCoverArt:(id)fp8;
- (void)_chapterPictureChanged:(id)fp8;
@end

