/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class BRControllerStack, BRMusicPlayer, BRRenderScene, NSTimer;

@interface BRMusicNowPlayingMonitor : NSObject
{
    BRMusicPlayer *_player;	// 4 = 0x4
    BRRenderScene *_scene;	// 8 = 0x8
    BRControllerStack *_stack;	// 12 = 0xc
    int _state;	// 16 = 0x10
    NSTimer *_returnToNowPlaying;	// 20 = 0x14
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)startMonitoringWithStack:(id)fp8;
- (void)stopMonitoring;

@end

