/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMediaMenuController.h>

#import "BRMenuListItemProviderProtocol.h"

@class BRMetadataPreviewController, BRMusicPlayer, NSArray, NSPredicate, NSString;

@interface BRMusicTracklistMenuController : BRMediaMenuController <BRMenuListItemProvider>
{
    id _playlist;	// 108 = 0x6c
    BRMusicPlayer *_player;	// 112 = 0x70
    NSArray *_tracklist;	// 116 = 0x74
    BRMetadataPreviewController *_cachedMDPreviewController;	// 120 = 0x78
    unsigned int _allowShuffleItem:1;	// 124 = 0x7c
    unsigned int _hasShuffleItem:1;	// 124 = 0x7c
    unsigned int _showUnplayedMark:1;	// 124 = 0x7c
    NSPredicate *_predicate;	// 128 = 0x80
    NSArray *_descriptors;	// 132 = 0x84
    NSString *_entityName;	// 136 = 0x88
}

- (id)initWithEntityName:(id)fp8 predicate:(id)fp12 sortDescriptors:(id)fp16 scene:(id)fp20;
- (void)dealloc;
- (void)setHasShuffleOption:(BOOL)fp8;
- (void)setHasUnplayedMarkOption:(BOOL)fp8;
- (BOOL)isVolatile;
- (void)refreshControllerForModelUpdate;
- (id)loadModelData;
- (BOOL)shouldRefreshForUpdateToObject:(id)fp8;
- (void)itemSelected:(long)fp8;
- (id)itemForRow:(long)fp8;
- (long)itemCount;
- (id)titleForRow:(long)fp8;
- (long)rowForTitle:(id)fp8;
- (id)previewControllerForItem:(long)fp8;
- (id)mediaPreviewMissingMediaType;
- (BOOL)mediaPreviewShouldShowMetadata;
- (BOOL)mediaPreviewShouldShowMetadataImmediately;

@end

