/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRFullscreenController.h>

@class BRMusicPlayer, BRMusicQCNowPlayingLayer, NSTimer;

@interface BRMusicNowPlayingController : BRFullscreenController
{
    BRMusicQCNowPlayingLayer *_layer;	// 32 = 0x20
    BRMusicPlayer *_player;	// 36 = 0x24
    NSTimer *_screenSaverUpdateTimer;	// 40 = 0x28
    unsigned int _layerInitialized:1;	// 44 = 0x2c
    unsigned int _allowsScreenSaver:1;	// 44 = 0x2c
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)wasPushed;
- (void)wasPopped;
- (void)willBeExhumed;
- (void)willBePushed;
- (void)willBePopped;
- (void)willBeBuried;
- (void)wasExhumedByPoppingController:(id)fp8;
- (void)resetLayout;

@end

