/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMediaMenuController.h>

#import "BRMenuListItemProviderProtocol.h"

@class NSArray;

@interface BRNetworkMediaMenuController : BRMediaMenuController <BRMenuListItemProvider>
{
    NSArray *_mediaAssets;	// 108 = 0x6c
    struct __CTTextTab *_rightTab;	// 112 = 0x70
    struct __CTTextTab *_leftTab;	// 116 = 0x74
}

- (id)initWithCollection:(id)fp8 scene:(id)fp12;
- (id)initWithMediaAssets:(id)fp8 scene:(id)fp12;
- (void)dealloc;
- (BOOL)isNetworkDependent;
- (void)wasExhumedByPoppingController:(id)fp8;
- (void)itemSelected:(long)fp8;
- (long)itemCount;
- (id)itemForRow:(long)fp8;
- (id)titleForRow:(long)fp8;
- (long)rowForTitle:(id)fp8;
- (id)previewControllerForItem:(long)fp8;

@end

