/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRParagraphTextLayer;

@interface BRParagraphTextControl : BRControl
{
    BRParagraphTextLayer *_layer;	// 8 = 0x8
    struct _NSRange _visibleRange;	// 12 = 0xc
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)readDocumentAtPath:(id)fp8 encoding:(unsigned int)fp12;
- (void)setAttributedString:(id)fp8;
- (void)displayTextStartingAtLine:(unsigned int)fp8;
- (void)displayTextEndingAtLine:(unsigned int)fp8;
- (id)attributedString;
- (struct _NSRange)visibleLineRange;
- (unsigned int)numLines;
- (id)layer;

@end

