/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderLayer.h>

@class NSArray, NSAttributedString;

@interface BRParagraphTextLayer : BRRenderLayer
{
    struct __CTTypesetter *_typesetter;	// 56 = 0x38
    NSAttributedString *_attributedString;	// 60 = 0x3c
    NSArray *_lines;	// 64 = 0x40
    struct _NSRange _visibleLineRange;	// 68 = 0x44
}

- (void)dealloc;
- (id)attributedString;
- (void)setAttributedString:(id)fp8;
- (void)displayTextStartingAtLine:(unsigned int)fp8;
- (void)displayTextEndingAtLine:(unsigned int)fp8;
- (struct _NSRange)visibleLineRange;
- (unsigned int)numLines;

@end

