/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRTexture.h>

@class BRRenderContext;

@interface BRPBufferTexture : BRTexture
{
    struct BRTextureInfo _info;	// 4 = 0x4
    BRRenderContext *_context;	// 52 = 0x34
    struct _CGLPBufferObject *_buffer;	// 56 = 0x38
}

- (id)initWithSize:(struct _NSSize)fp8 sharedContext:(id)fp16;
- (id)initWithSize:(struct _NSSize)fp8 sharedContext:(id)fp16 pixelFormat:(id)fp20;
- (void)dealloc;
- (id)textureContext;
- (const struct BRTextureInfo *)textureInfo;

@end

