/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class BRPhloatoArtLoader, NSMutableArray;

@interface BRPhloatoPlane : NSObject
{
    BRPhloatoArtLoader *_provider;	// 4 = 0x4
    struct BRPhloatoPlaneImagePosition *_table;	// 8 = 0x8
    NSMutableArray *_imageStructures;	// 12 = 0xc
    long _currentEntryIndex;	// 16 = 0x10
    long _entryCount;	// 20 = 0x14
    double _timeUntilNextLoad;	// 24 = 0x18
    double _retirementPosition;	// 32 = 0x20
    double _startPosition;	// 40 = 0x28
}

- (id)initWithPositionTable:(const struct BRPhloatoPlaneImagePosition *)fp8 count:(long)fp12;
- (void)dealloc;
- (void)setProvider:(id)fp8;
- (void)setViewRect:(struct _NSRect)fp8;
- (void)updatePositions:(double)fp8;
- (id)imageStructures;

@end

