/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMediaPlayerController.h>

@class BRBlackFadeoutLayer, BRPhotoPlayer, BRPhotoPlayerHostLayer, NSArray;

@interface BRPhotoPlayerController : BRMediaPlayerController
{
    BRPhotoPlayer *_player;	// 24 = 0x18
    BRPhotoPlayerHostLayer *_host;	// 28 = 0x1c
    BRBlackFadeoutLayer *_fade;	// 32 = 0x20
    NSArray *_savedLayers;	// 36 = 0x24
}

- (void)dealloc;
- (void)resetLayout;
- (void)setPhotoPlayer:(id)fp8;
- (id)photoPlayer;
- (id)player;
- (void)willBePushed;
- (void)wasPushed;
- (void)willBePopped;
- (void)wasPopped;
- (void)wasExhumedByPoppingController:(id)fp8;
- (void)willBeExhumed;
- (void)willBeBuried;
- (id)popAnimation;
- (id)pushAnimation;
- (id)exhumeAnimationWithPoppingController:(id)fp8;
- (id)buryAnimationWithPushingController:(id)fp8;
- (BOOL)brEventAction:(id)fp8;

@end

