/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMediaMenuController.h>

#import "BRMenuListItemProviderProtocol.h"

@class BRIconPreviewController, NSArray;

@interface BRPhotoController : BRMediaMenuController <BRMenuListItemProvider>
{
    id _collection;	// 108 = 0x6c
    NSArray *_itemList;	// 112 = 0x70
    BRIconPreviewController *_noSyncedContentController;	// 116 = 0x74
}

- (id)initWithScene:(id)fp8 error:(id *)fp12;
- (void)dealloc;
- (id)mediaProvider;
- (long)defaultIndex;
- (id)collection;
- (void)setCollection:(id)fp8 error:(id *)fp12;
- (void)itemSelected:(long)fp8;
- (id)itemForRow:(long)fp8;
- (long)itemCount;
- (id)titleForRow:(long)fp8;
- (long)rowForTitle:(id)fp8;
- (void)wasExhumedByPoppingController:(id)fp8;
- (id)previewControllerForItem:(long)fp8;
- (id)mediaPreviewMissingMediaType;

@end

