/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import "BRScreenSaverPluginProtocolProtocol.h"

@class BRPhloatoArtLoader, BRPhloatoLayer;

@interface BRPhloatoScreenSaver : NSObject <BRScreenSaverPluginProtocol>
{
    BRPhloatoLayer *_layer;	// 4 = 0x4
    BRPhloatoArtLoader *_frontProvider;	// 8 = 0x8
    BRPhloatoArtLoader *_middleProvider;	// 12 = 0xc
    BRPhloatoArtLoader *_backProvider;	// 16 = 0x10
    unsigned int _waitingForQueue:1;	// 20 = 0x14
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (id)layer;
- (void)activate;
- (void)deactivate;
- (long)minimumAssets;
- (void)setAssets:(id)fp8;
- (id)loadAssets;

@end

