/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRPhotoController.h>

@interface BRPhotoController (BRPhotoControllerContent)
- (BOOL)_hasSettingsItem;
- (id)_currentItemList;
- (void)_updateMediaParadeSource;
- (void)_setItemList:(id)fp8;
- (id)_mediaListForCollection:(id)fp8 fromProvider:(id)fp12;
- (id)_grabPhotosForCollection:(id)fp8;
- (id)_buildSettingsMenu;
@end

