/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderLayer.h>

@class BRPhotoPlayer, BRPhotoTexture;

@interface BRPhotoPlayerHostLayer : BRRenderLayer
{
    BRPhotoPlayer *_player;	// 56 = 0x38
    BRPhotoTexture *_texture;	// 60 = 0x3c
}

- (void)dealloc;
- (void)setPlayer:(id)fp8;
- (id)player;
- (BOOL)updateFrameForTime:(const CVTimeStamp *)fp8;
- (void)renderLayer;

@end

