/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRQuartzComposerLayer.h>

@class BRPhloatoPlane;

@interface BRPhloatoLayer : BRQuartzComposerLayer
{
    BRPhloatoPlane *_frontPlane;	// 92 = 0x5c
    BRPhloatoPlane *_middlePlane;	// 96 = 0x60
    BRPhloatoPlane *_backPlane;	// 100 = 0x64
    double _updateTimeFreq;	// 104 = 0x68
    double _prevTime;	// 112 = 0x70
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)setFrame:(struct _NSRect)fp8;
- (void)setFrontProvider:(id)fp8;
- (void)setMiddleProvider:(id)fp8;
- (void)setBackProvider:(id)fp8;
- (BOOL)updateFrameForTime:(const CVTimeStamp *)fp8;

@end

