/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRTexture.h>

@class PATexture;

@interface BRPhotoTexture : BRTexture
{
    struct BRTextureInfo *_textureInfo;	// 4 = 0x4
    PATexture *_paTexture;	// 8 = 0x8
}

- (id)initWithPATexture:(id)fp8;
- (void)dealloc;
- (const struct BRTextureInfo *)textureInfo;

@end

