/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRLayerController.h>

@interface BRPostedAlertController : BRLayerController
{
}

+ (void)postModalAlertNotificationOfType:(id)fp8 withInfo:(id)fp12;
+ (id)modalAlertFromNotification:(id)fp8 inScene:(id)fp12;

@end

