/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRPostedAlertController.h>

@interface BRPostedAlertController (Private)
+ (id)_alertForSWUpdateConfirmationWithInfo:(id)fp8 withScene:(id)fp12;
+ (void)_postModalAlertNotificationWithInfo:(id)fp8;
@end

