/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import "BRScreenSaverPluginProtocolProtocol.h"

@class BRQuartzComposerLayer;

@interface BRQCScreenSaver : NSObject <BRScreenSaverPluginProtocol>
{
    BRQuartzComposerLayer *_layer;	// 4 = 0x4
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (id)layer;
- (void)activate;
- (void)deactivate;
- (BOOL)setCompositionPath:(id)fp8;
- (BOOL)setValue:(id)fp8 forInputKey:(id)fp12;

@end

