/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRQuartzComposerLayer;

@interface BRQuartzComposerControl : BRControl
{
    BRQuartzComposerLayer *_layer;	// 8 = 0x8
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (BOOL)setCompositionPath:(id)fp8;
- (void)startAnimation;
- (void)stopAnimation;
- (BOOL)setValue:(id)fp8 forInputKey:(id)fp12;
- (id)layer;

@end

