/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderLayer.h>

@class QCOpenGLContext, QCPatch;

@interface BRQuartzComposerLayer : BRRenderLayer
{
    QCPatch *_patch;	// 56 = 0x38
    QCOpenGLContext *_qcContext;	// 60 = 0x3c
    double _timeFreq;	// 64 = 0x40
    double _startTime;	// 72 = 0x48
    double _timeDiff;	// 80 = 0x50
    unsigned int _fullscreen:1;	// 88 = 0x58
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (BOOL)setCompositionPath:(id)fp8;
- (BOOL)setValue:(id)fp8 forInputKey:(id)fp12;
- (id)valueForInputKey:(id)fp8;
- (struct _NSRect)boundingBox;
- (void)setFrame:(struct _NSRect)fp8;
- (BOOL)updateFrameForTime:(const CVTimeStamp *)fp8;
- (void)renderLayer;

@end

