/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderLayer.h>

@interface BRQuadLayer : BRRenderLayer
{
    float _color[3];	// 56 = 0x38
}

- (void)setRedColor:(float)fp8 greenColor:(float)fp12 blueColor:(float)fp16;
- (void)renderLayer;

@end

