/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRQuartzComposerLayer.h>

@interface BRQuartzComposerLayer (RenderContext)
- (void)_updateQCContext;
- (void)_disposeQCContext;
- (void)_renderSubscreen;
@end

