/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class BRRenderScene, NSMutableSet;

@interface BRRenderDisplayLink : NSObject
{
    BRRenderScene *_scene;	// 4 = 0x4
    NSMutableSet *_items;	// 8 = 0x8
    struct __CVDisplayLink *_link;	// 12 = 0xc
    long _frameCount;	// 16 = 0x10
    double _frameTimeAccum;	// 20 = 0x14
    double _prevFrameTime;	// 28 = 0x1c
    unsigned int _needsDisplay:1;	// 36 = 0x24
    unsigned int _stopFakeThread:1;	// 36 = 0x24
    unsigned int _beamSyncDisabled:1;	// 36 = 0x24
    unsigned int _updateFramerate:1;	// 36 = 0x24
    unsigned int _logItems:1;	// 36 = 0x24
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)needsDisplay;
- (void)setUpdateFramerate:(BOOL)fp8;
- (void)addItemToLink:(id)fp8;
- (void)removeLinkItem:(id)fp8;
- (BOOL)isRunning;

@end

