/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class BRRenderPixelFormat;

@interface BRRenderContext : NSObject
{
    BRRenderPixelFormat *_format;	// 4 = 0x4
    BRRenderContext *_shared;	// 8 = 0x8
    struct _CGLContextObject *_context;	// 12 = 0xc
}

- (id)initWithPixelFormat:(id)fp8 sharedContext:(id)fp12;
- (id)pixelFormat;
- (struct _CGLContextObject *)CGLContext;
- (void)dealloc;

@end

