/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import "BRDisplayLinkItemProtocol.h"

@class BRPBufferTexture, BRRenderContext, BRRenderScene, NSMutableArray;

@interface BRRenderLayer : NSObject <BRDisplayLinkItem>
{
    BRRenderScene *_scene;	// 4 = 0x4
    BRRenderContext *_context;	// 8 = 0x8
    BRRenderLayer *_superlayer;	// 12 = 0xc
    NSMutableArray *_sublayers;	// 16 = 0x10
    id _effectsDelegate;	// 20 = 0x14
    BRPBufferTexture *_effectsTexture;	// 24 = 0x18
    float _zPosition;	// 28 = 0x1c
    struct _NSRect _frame;	// 32 = 0x20
    float _alpha;	// 48 = 0x30
    unsigned int _needsUpdates:1;	// 52 = 0x34
    unsigned int _clipsAtFrame:1;	// 52 = 0x34
    unsigned int _hidden:1;	// 52 = 0x34
    unsigned int _drawFrameOutline:1;	// 52 = 0x34
}

+ (id)layerWithScene:(id)fp8;
- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (id)scene;
- (void)setEffectsDelegate:(id)fp8;
- (id)effectsDelegate;
- (id)context;
- (BOOL)clipsToFrame;
- (void)setHidden:(BOOL)fp8;
- (BOOL)hidden;
- (id)superlayer;
- (id)sublayers;
- (void)setSublayers:(id)fp8;
- (void)removeFromSuperlayer;
- (void)addSublayer:(id)fp8;
- (void)insertSublayer:(id)fp8 atIndex:(long)fp12;
- (void)insertSublayer:(id)fp8 below:(id)fp12;
- (void)insertSublayer:(id)fp8 above:(id)fp12;
- (void)replaceSublayer:(id)fp8 with:(id)fp12;
- (void)setAlphaValue:(float)fp8;
- (float)alphaValue;
- (void)setFrame:(struct _NSRect)fp8;
- (struct _NSRect)frame;
- (void)setZPosition:(float)fp8;
- (float)zPosition;
- (void)setNeedsUpdates:(BOOL)fp8;
- (BOOL)needsUpdates;
- (BOOL)updateFrameForTime:(const CVTimeStamp *)fp8;
- (void)renderLayer;

@end

