/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@interface BRRenderer : NSObject
{
}

- (id)scene;
- (void)orderOut;
- (void)orderIn;
- (void)displayOnline;
- (void)displayOffline;
- (void)displayCanvasChanged;

@end

