/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class BRRenderContext, BRRenderDisplayLink, BRRenderLayer, NSMutableDictionary;

@interface BRRenderScene : NSObject
{
    BRRenderContext *_context;	// 4 = 0x4
    BRRenderContext *_resourceContext;	// 8 = 0x8
    BRRenderLayer *_root;	// 12 = 0xc
    struct _NSSize _sceneSize;	// 16 = 0x10
    unsigned int _setupList;	// 24 = 0x18
    BRRenderDisplayLink *_displayLink;	// 28 = 0x1c
    NSMutableDictionary *_textureCache;	// 32 = 0x20
    float _backupDistance;	// 36 = 0x24
    float _backClipping;	// 40 = 0x28
    float _frontClipping;	// 44 = 0x2c
    float _aspectRatio;	// 48 = 0x30
    float _fov;	// 52 = 0x34
    unsigned int _opaque:1;	// 56 = 0x38
    unsigned int _dumpTree:1;	// 56 = 0x38
    unsigned int _drawFrameRate:1;	// 56 = 0x38
    unsigned int _drawSafeRegions:1;	// 56 = 0x38
    double _frameRate;	// 60 = 0x3c
    long _perfFrameCount;	// 68 = 0x44
    double _perfMarkTime;	// 72 = 0x48
    unsigned int _perfLoggingEnabled:1;	// 80 = 0x50
}

- (id)init;
- (void)dealloc;
- (void)setDrawableContext:(id)fp8;
- (void)setSize:(struct _NSSize)fp8;
- (struct _NSSize)size;
- (struct _NSRect)interfaceFrame;
- (void)setRoot:(id)fp8;
- (id)root;
- (void)renderScene;
- (id)displayLink;
- (id)resourceContext;
- (id)cachedTextureForKey:(id)fp8;
- (void)setCachedTexture:(id)fp8 forKey:(id)fp12;
- (void)resetCachedTextures;
- (float)backClipping;
- (float)frontClipping;
- (id)qcContext;
- (void)perfMarkTime;
- (void)perfLogTimeDiffWithMessage:(id)fp8;

@end

