/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderLayer.h>

@class NSData;

@interface BRRoundRectOutlineLayer : BRRenderLayer
{
    float _cornerRadius;	// 56 = 0x38
    float _rgba[4];	// 60 = 0x3c
    unsigned int _displayListID;	// 76 = 0x4c
    unsigned int _cornerTextureID;	// 80 = 0x50
    NSData *_cornerData;	// 84 = 0x54
    float _lineWidth;	// 88 = 0x58
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)setRedColor:(float)fp8 greenColor:(float)fp12 blueColor:(float)fp16;
- (void)setFrame:(struct _NSRect)fp8;
- (void)setCornerRadius:(float)fp8;
- (float)cornerRadius;
- (float)lineWidth;
- (void)setLineWidth:(float)fp8;
- (void)renderLayer;
- (struct _NSRect)frameForContentFrame:(struct _NSRect)fp8;

@end

