/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRImageLayer, BRRenderLayer, BRTexture;

@interface BRScrollBarControl : BRControl
{
    BRRenderLayer *_layer;	// 8 = 0x8
    BRImageLayer *_upArrow;	// 12 = 0xc
    BRImageLayer *_downArrow;	// 16 = 0x10
    BRTexture *_fullUpArrow;	// 20 = 0x14
    BRTexture *_emptyUpArrow;	// 24 = 0x18
    BRTexture *_fullDownArrow;	// 28 = 0x1c
    BRTexture *_emptyDownArrow;	// 32 = 0x20
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)setUpArrowEnabled:(BOOL)fp8;
- (void)setDownArrowEnabled:(BOOL)fp8;
- (id)layer;
- (void)setFrame:(struct _NSRect)fp8;

@end

