/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRFullscreenController.h>

@class BRRenderLayer, BRTrackInfoControl;

@interface BRScreenSaverController : BRFullscreenController
{
    id _plugin;	// 32 = 0x20
    BRTrackInfoControl *_trackInfo;	// 36 = 0x24
    BRRenderLayer *_pluginLayer;	// 40 = 0x28
    unsigned int _pluginActive:1;	// 44 = 0x2c
}

+ (id)screenSaverControllerWithScene:(id)fp8 andPlugin:(id)fp12;
- (id)initWithScene:(id)fp8 andPlugin:(id)fp12;
- (void)dealloc;
- (BOOL)brEventAction:(id)fp8;
- (void)wasPushed;
- (void)wasPopped;
- (void)wasExhumedByPoppingController:(id)fp8;
- (void)wasBuriedByPushingController:(id)fp8;
- (struct _NSRect)masterLayerFrame;
- (void)resetLayout;
- (BOOL)popsOnBury;

@end

