/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@class NSTimer;

@interface BRScreenSaverManager : BRSingleton
{
    NSTimer *_timer;	// 4 = 0x4
    double _interval;	// 8 = 0x8
    unsigned int _enabled:1;	// 16 = 0x10
    unsigned int _screenSaverPosted:1;	// 16 = 0x10
}

+ (id)singleton;
+ (void)setSingleton:(id)fp8;
- (id)init;
- (void)dealloc;
- (void)updateActivity;
- (void)enable;
- (id)controllerWithScene:(id)fp8;
- (id)screenSaverPluginWithScene:(id)fp8 path:(id)fp12;
- (id)screenSaverPathsFromDirectory:(id)fp8;

@end

