/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRSettingsHelper.h>

@interface BRSettingsHelper (Private)
- (BOOL)_helperPerform:(struct SHCommandInfo *)fp8;
- (int)_initialBootCount;
@end

