/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRCenteredMenuController.h>

#import "BRMenuListItemProviderProtocol.h"

@interface BRSettingsiTunesPairingWarningController : BRCenteredMenuController <BRMenuListItemProvider>
{
    int _type;	// 136 = 0x88
}

+ (id)warningControllerForTurningOffSyncWithScene:(id)fp8;
+ (id)warningControllerForChangingSyncHostWithScene:(id)fp8;
- (void)itemSelected:(long)fp8;
- (id)itemForRow:(long)fp8;
- (long)itemCount;
- (id)titleForRow:(long)fp8;
- (long)rowForTitle:(id)fp8;

@end

