/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderLayer.h>

@class BRTexture, BRWaitSpinnerLayer;

@interface BRSelectionLozengeLayer : BRRenderLayer
{
    BRTexture *_leftImage;	// 56 = 0x38
    BRTexture *_rightImage;	// 60 = 0x3c
    BRTexture *_centerImage;	// 64 = 0x40
    unsigned int _displayListID;	// 68 = 0x44
    BRWaitSpinnerLayer *_spinner;	// 72 = 0x48
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)setFrame:(struct _NSRect)fp8;
- (float)overHangForRowHeight:(float)fp8;
- (float)underHangForRowHeight:(float)fp8;
- (float)overHeightFactor;
- (id)waitSpinner;
- (void)renderLayer;

@end

