/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@interface BRSettingsHelper : BRSingleton
{
    struct AuthorizationOpaqueRef *_authRef;	// 4 = 0x4
}

+ (id)singleton;
+ (void)setSingleton:(id)fp8;
- (id)init;
- (void)dealloc;
- (BOOL)setSystemLanguage:(id)fp8;
- (BOOL)setNetworkSettings:(id)fp8 forInterface:(int)fp12;
- (BOOL)setLowPowerMode:(BOOL)fp8;
- (BOOL)setTimeZoneOffsetSecsFromGMT:(int)fp8;
- (BOOL)performOSUpdate:(BOOL)fp8 EFIUpdate:(BOOL)fp12 IRUpdate:(BOOL)fp16 SIUpdate:(BOOL)fp20;
- (BOOL)prepareForFactoryRestore;
- (BOOL)tellWatchdogWeAreUpAndRunning;
- (BOOL)haveWeQuitSinceBoot;
- (void)reboot;

@end

