/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@class BRControllerStack;

@interface BRSentinel : BRSingleton
{
    id _musicStoreImageDecryptionAgent;	// 4 = 0x4
    id _drmSyncAgent;	// 8 = 0x8
    id _syncProgressAgent;	// 12 = 0xc
    BRControllerStack *_controllerStack;	// 16 = 0x10
    unsigned int _networkDependentControllerCount;	// 20 = 0x14
}

+ (id)singleton;
+ (void)setSingleton:(id)fp8;
- (id)init;
- (void)dealloc;
- (void)setMusicStoreImageDecryptionAgent:(id)fp8;
- (id)musicStoreImageDecryptionAgent;
- (void)setCurrentControllerStack:(id)fp8;
- (void)networkDependentControllerWillBePushed;
- (void)networkDependentControllerWasPopped;
- (void)setDRMSyncAgent:(id)fp8;
- (id)drmSyncAgent;
- (void)setSyncProgressAgent:(id)fp8;
- (id)syncProgressAgent;

@end

