/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class BRIPConfiguration, DMDisk;

@interface BRSettingsFacade : NSObject
{
    BRIPConfiguration *_ipConfiguration;	// 4 = 0x4
    DMDisk *_disk;	// 8 = 0x8
}

+ (id)settingsFacade;
+ (id)placeProductImageForScene:(id)fp8 masterLayer:(id)fp12;
+ (unsigned long long)mediaPartitionReservedBytes;
+ (unsigned long long)mediaPartitionReservedStreamingBufferBytes;
- (void)resetAllSettings;
- (void)dealloc;
- (id)deviceName;
- (void)setDeviceName:(id)fp8;
- (id)serialNumber;
- (id)tvResolution;
- (id)machineModel;
- (id)mediaPartitionCapacity;
- (id)mediaPartitionFreeSpace;
- (id)mediaPartitionCapacityString;
- (id)mediaPartitionFreeSpaceString;
- (BOOL)soundEnabled;
- (void)setSoundEnabled:(BOOL)fp8;
- (id)screenSaverPathsArray;
- (id)screenSaverPath;
- (void)setScreenSaverPath:(id)fp8;
- (int)screenSaverTimeout;
- (void)setScreenSaverTimeout:(int)fp8;
- (BOOL)allowScreenSaverOverMusic;
- (void)setAllowScreenSaverOverMusic:(BOOL)fp8;
- (int)phloatoSpinFrequency;
- (BOOL)isWiredActive;
- (BOOL)isWirelessActive;
- (BOOL)wiredUsesDHCP;
- (BOOL)wirelessUsesDHCP;
- (id)wiredMACaddress;
- (id)wirelessMACaddress;
- (id)wiredIPaddress;
- (id)wirelessIPaddress;
- (long)wirelessSignalQuality;
- (id)wirelessNetwork;
- (void)refreshIPConfig;
- (void)pairRemote;
- (void)unpairRemote;
- (BOOL)isPairedRemote;
- (void)standby;
- (BOOL)closedCaptionEnabled;
- (void)setClosedCaptionEnabled:(BOOL)fp8;
- (long)numberOfSongs;
- (long)numberOfVideos;
- (long)numberOfPhotos;
- (int)slideshowSecondsPerSlide;
- (void)setSlideshowSecondsPerSlide:(int)fp8;
- (BOOL)slideshowRepeat;
- (void)setSlideshowRepeat:(BOOL)fp8;
- (BOOL)slideshowShufflePhotos;
- (void)setSlideshowShufflePhotos:(BOOL)fp8;
- (BOOL)slideshowShuffleMusic;
- (void)setSlideshowShuffleMusic:(BOOL)fp8;
- (BOOL)slideshowPanAndZoom;
- (void)setSlideshowPanAndZoom:(BOOL)fp8;
- (BOOL)slideshowPlayMusic;
- (void)setSlideshowPlayMusic:(BOOL)fp8;
- (id)slideshowPlaylists;
- (id)slideshowPlaylistName;
- (void)setSlideshowPlaylistName:(id)fp8;
- (BOOL)slideshowUseNowPlayingMusic;
- (void)setSlideshowUseNowPlayingMusic:(BOOL)fp8;
- (id)slideshowTransitionNameList;
- (id)slideshowTransitionName;
- (void)setSlideshowTransitionName:(id)fp8;
- (id)slideshowTransitionDirection;
- (void)setSlideshowTransitionDirection:(id)fp8;
- (BOOL)slideshowTransitionsDisabled;
- (BOOL)slideshowTransitionsRandom;
- (id)slideshowPlaybackOptions;
- (BOOL)isSynced;
- (id)syncHostName;
- (BOOL)disableTurnOffSyncing;
- (BOOL)musicPlaybackUsesSoundCheck;
- (void)setMusicPlaybackUsesSoundCheck:(BOOL)fp8;
- (int)musicRepeatMode;
- (void)setMusicRepeatMode:(int)fp8;
- (BOOL)rangeLimitedHDMI;
- (void)setRangeLimitedHDMI:(BOOL)fp8;
- (id)softwareVersion;
- (id)softwareBuild;
- (id)osVersion;
- (id)efiVersion;
- (id)irVersion;
- (id)siVersion;

@end

