/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRStatusAlertController.h>

@interface BRStatusAlertController (Private)
+ (void)_postStatusAlertNotificationOfType:(id)fp8;
- (void)_showStatusAlertForType:(id)fp8 inLayer:(id)fp12;
- (void)_startSyncAnimationInLayer:(id)fp8;
- (void)_runPairingHUDAlertInLayer:(id)fp8 hudType:(int)fp12;
@end

