/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSBundle;

@interface BRSystemLanguages : NSObject
{
    NSBundle *_promptBundle;	// 4 = 0x4
    NSBundle *_refBundle;	// 8 = 0x8
}

+ (id)currentLanguage;
- (id)init;
- (void)dealloc;
- (id)getLangsAndPrompts:(BOOL)fp8;
- (BOOL)setSystemLanguage:(id)fp8;

@end

