/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRProgressBarWidget, BRRenderLayer, BRTextControl, NSString;

@interface BRSyncProgressControl : BRControl
{
    BRRenderLayer *_layer;	// 8 = 0x8
    BRProgressBarWidget *_progressBar;	// 12 = 0xc
    BRTextControl *_sourceText;	// 16 = 0x10
    BRTextControl *_currentAssetText;	// 20 = 0x14
    NSString *_currentAssetTextFormat;	// 24 = 0x18
    unsigned int _numAssets;	// 28 = 0x1c
}

- (id)initWithScene:(id)fp8 width:(float)fp12 sourceName:(id)fp16 notification:(id)fp20;
- (void)dealloc;
- (id)layer;
- (void)setCurrentAssetName:(id)fp8 num:(unsigned int)fp12;
- (void)setPercentage:(float)fp8;
- (void)_updateProgress:(id)fp8;

@end

