/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRCenteredMenuController.h>

#import "BRDottedQuadEntryDelegateProtocol.h"
#import "BRMenuListItemProviderProtocol.h"

@class BRDottedQuadEntryController, NSString;

@interface BRTCPIPConfigController : BRCenteredMenuController <BRMenuListItemProvider, BRDottedQuadEntryDelegate>
{
    id _delegate;	// 136 = 0x88
    NSString *_address;	// 140 = 0x8c
    NSString *_subnetMask;	// 144 = 0x90
    NSString *_router;	// 148 = 0x94
    NSString *_dns;	// 152 = 0x98
    BRDottedQuadEntryController *_ipController;	// 156 = 0x9c
    BRDottedQuadEntryController *_maskController;	// 160 = 0xa0
    BRDottedQuadEntryController *_routerController;	// 164 = 0xa4
    BRDottedQuadEntryController *_dnsController;	// 168 = 0xa8
    unsigned int _forWireless:1;	// 172 = 0xac
    unsigned int _useDHCP:1;	// 172 = 0xac
}

- (id)initWithScene:(id)fp8 forWireless:(BOOL)fp12 showBack:(BOOL)fp16 notifying:(id)fp20;
- (void)dealloc;
- (void)itemSelected:(long)fp8;
- (id)itemForRow:(long)fp8;
- (long)itemCount;
- (id)titleForRow:(long)fp8;
- (long)rowForTitle:(id)fp8;
- (void)entryComplete:(id)fp8;

@end

