/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRTextLayer, NSDictionary;

@interface BRTextControl : BRControl
{
    BRTextLayer *_layer;	// 8 = 0x8
    NSDictionary *_attributes;	// 12 = 0xc
    unsigned int _maxLines;	// 16 = 0x10
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)setTextAttributes:(id)fp8;
- (id)textAttributes;
- (void)setText:(id)fp8;
- (id)text;
- (struct _NSSize)renderedSize;
- (void)setMaximumSize:(struct _NSSize)fp8;
- (struct _NSSize)maximumSize;
- (id)layer;
- (void)setFrame:(struct _NSRect)fp8;
- (void)setMaxLines:(unsigned int)fp8;
- (unsigned int)maxLines;
- (BOOL)isMultiLine;

@end

