/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderLayer.h>

@class BRTexture, NSAttributedString;

@interface BRTextLayer : BRRenderLayer
{
    NSAttributedString *_string;	// 56 = 0x38
    struct __CTFramesetter *_framesetter;	// 60 = 0x3c
    struct __CTTypesetter *_typesetter;	// 64 = 0x40
    struct __CTLine *_truncationToken;	// 68 = 0x44
    struct _NSSize _maxSize;	// 72 = 0x48
    struct _NSSize _textureSize;	// 80 = 0x50
    struct _NSSize _textureFramedSize;	// 88 = 0x58
    BRTexture *_texture;	// 96 = 0x60
    unsigned int _colorText:1;	// 100 = 0x64
}

- (void)dealloc;
- (void)setMaxSize:(struct _NSSize)fp8;
- (struct _NSSize)maxSize;
- (struct _NSSize)renderedSize;
- (id)texture;
- (void)setAttributedString:(id)fp8;
- (id)attributedString;
- (void)setColorText:(BOOL)fp8;
- (BOOL)colorText;
- (void)renderLayer;

@end

