/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

#import "BRTextContainerProtocol.h"

@class BRCharacterSelectionLayer, BRRenderLayer, BRScrollableTextLayer, BRTextFieldBackgroundLayer, BRTextLayer, NSMutableString;

@interface BRTextEntryControl : BRControl <BRTextContainer>
{
    BRRenderLayer *_masterLayer;	// 8 = 0x8
    BRScrollableTextLayer *_textField;	// 12 = 0xc
    BRTextLayer *_textFieldLabel;	// 16 = 0x10
    BRTextFieldBackgroundLayer *_textFieldBackground;	// 20 = 0x14
    BRCharacterSelectionLayer *_characterSelector;	// 24 = 0x18
    NSMutableString *_userEnteredText;	// 28 = 0x1c
    struct _NSSize _screenSize;	// 32 = 0x20
    id _textEntryCompleteDelegate;	// 40 = 0x28
}

- (id)initWithScene:(id)fp8;
- (id)initWithScene:(id)fp8 hexInputOnly:(BOOL)fp12;
- (void)dealloc;
- (void)setFrameFromScreenSize:(struct _NSSize)fp8;
- (void)setTextFieldLabel:(id)fp8;
- (void)setTextEntryCompleteDelegate:(id)fp8;
- (void)setInitialText:(id)fp8;
- (void)reset;
- (id)stringValue;
- (id)layer;
- (void)setFrame:(struct _NSRect)fp8;
- (BOOL)brEventAction:(id)fp8;

@end

