/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRTextLayer.h>

@interface BRTextLayer (PathRendering)
- (void)_flushCaches;
- (struct __CTFramesetter *)_framesetter;
- (struct __CTTypesetter *)_typesetter;
- (struct __CTLine *)_truncationToken;
- (void)_draw:(struct CGContext *)fp8;
- (void)_drawTruncated:(unsigned char)fp8 alignment:(unsigned char)fp12 inContext:(struct CGContext *)fp16;
- (void)_drawAligned:(unsigned char)fp8 inContext:(struct CGContext *)fp12;
@end

