/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@interface BRTexture : NSObject
{
}

- (const struct BRTextureInfo *)textureInfo;
- (void)render;
- (void)renderInRect:(struct _NSRect)fp8;

@end

