/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderLayer.h>

@class BRImageLayer, BRRoundRectLayer, NSArray;

@interface BRTrackInfoLayer : BRRenderLayer
{
    BRRoundRectLayer *_background;	// 56 = 0x38
    BRImageLayer *_art;	// 60 = 0x3c
    NSArray *_lines;	// 64 = 0x40
    float _maxLength;	// 68 = 0x44
    long _maxLines;	// 72 = 0x48
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)setAlphaValue:(float)fp8;
- (void)setFrame:(struct _NSRect)fp8;
- (void)setLines:(id)fp8 withImage:(struct CGImage *)fp12;
- (void)setImage:(struct CGImage *)fp8;
- (void)setMaxLines:(long)fp8;

@end

