/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderLayer.h>

@class BRBitmapTexture, BRTextLayer, BRWaitSpinnerLayer, NSMutableDictionary, NSString;

@interface BRTransportLayer : BRRenderLayer
{
    double _duration;	// 56 = 0x38
    double _elapsedTime;	// 64 = 0x40
    float _percentComplete;	// 72 = 0x48
    struct _NSRange _downloadedRange;	// 76 = 0x4c
    int _currentState;	// 84 = 0x54
    NSString *_currentChapter;	// 88 = 0x58
    NSMutableDictionary *_cachedTextures;	// 92 = 0x5c
    struct _NSRect _leftEndCapBounds;	// 96 = 0x60
    struct _NSRect _rightEndCapBounds;	// 112 = 0x70
    BRBitmapTexture *_leftEndCap;	// 128 = 0x80
    BRBitmapTexture *_rightEndCap;	// 132 = 0x84
    struct _NSRect _leftProgressEndCapBounds;	// 136 = 0x88
    struct _NSRect _rightProgressEndCapBounds;	// 152 = 0x98
    BRBitmapTexture *_leftProgressEndCap;	// 168 = 0xa8
    BRBitmapTexture *_rightProgressEndCap;	// 172 = 0xac
    long _downloadedRectCount;	// 176 = 0xb0
    struct _NSRect _downloadedRects[1];	// 180 = 0xb4
    BRBitmapTexture *_downloaded;	// 196 = 0xc4
    long _undownloadedRectCount;	// 200 = 0xc8
    struct _NSRect _undownloadedRects[2];	// 204 = 0xcc
    BRBitmapTexture *_undownloaded;	// 236 = 0xec
    struct _NSRect _playheadBounds;	// 240 = 0xf0
    BRBitmapTexture *_playhead;	// 256 = 0x100
    BRTextLayer *_currentTimeTextLayer;	// 260 = 0x104
    BRTextLayer *_currentChapterTextLayer;	// 264 = 0x108
    BRTextLayer *_durationTextLayer;	// 268 = 0x10c
    BRWaitSpinnerLayer *_spinner;	// 272 = 0x110
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)setState:(int)fp8;
- (BOOL)setElapsedTime:(double)fp8;
- (void)setDuration:(double)fp8;
- (void)setDownloadedRange:(struct _NSRange)fp8;
- (void)setChapterString:(id)fp8;
- (void)setFrame:(struct _NSRect)fp8;
- (void)renderLayer;

@end

