/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRBaseParserDelegate.h>

@class BRMovieTrailer, BRMovieTrailersProvider, BRResolution, NSMutableArray, NSXMLParser;

@interface BRTrailerDelegate : BRBaseParserDelegate
{
    BRMovieTrailersProvider *_provider;	// 8 = 0x8
    BRMovieTrailer *_movieTrailer;	// 12 = 0xc
    NSMutableArray *_elementCollection;	// 16 = 0x10
    BRResolution *_resolution;	// 20 = 0x14
    NSXMLParser *_parser;	// 24 = 0x18
}

- (id)initWithMediaProvider:(id)fp8 resolution:(id)fp12;
- (void)dealloc;
- (void)setWeakReferenceToParser:(id)fp8;
- (void)startMovieinfoWithAttributes:(id)fp8;
- (void)endMovieinfo;
- (void)endTitle;
- (void)endRuntime;
- (void)endRating;
- (void)endStudio;
- (void)endPostdate;
- (void)endReleasedate;
- (void)endCopyright;
- (void)endDirector;
- (void)endDescription;
- (void)endName;
- (void)startCastWithAttributes:(id)fp8;
- (void)endCast;
- (void)startGenreWithAttributes:(id)fp8;
- (void)endGenre;
- (void)endLocation;
- (void)endXlarge;
- (void)endPoster;
- (void)endLarge;

@end

