/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRAnimation, BRMusicPlayer, BRTrackInfoLayer, NSString, NSTimer;

@interface BRTrackInfoControl : BRControl
{
    BRTrackInfoLayer *_layer;	// 8 = 0x8
    BRMusicPlayer *_player;	// 12 = 0xc
    NSString *_lastAssetID;	// 16 = 0x10
    NSTimer *_hideTimer;	// 20 = 0x14
    BRAnimation *_fade;	// 24 = 0x18
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (id)layer;
- (BOOL)brEventAction:(id)fp8;
- (void)activate;
- (void)deactivate;

@end

