/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRTransportLayer, BRValueAnimation, BRVideoPlayer, NSTimer;

@interface BRTransportControl : BRControl
{
    BRVideoPlayer *_player;	// 8 = 0x8
    BRTransportLayer *_layer;	// 12 = 0xc
    BRValueAnimation *_fadeAnimation;	// 16 = 0x10
    NSTimer *_fadeTimer;	// 20 = 0x14
    unsigned int _alreadyHaveStartedPlayback:1;	// 24 = 0x18
    unsigned int _useBufferedRange:1;	// 24 = 0x18
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)setPlayer:(id)fp8;
- (struct _NSRect)transportFrameForVideoFrame:(struct _NSRect)fp8;
- (id)layer;
- (void)setHidden:(BOOL)fp8;

@end

