/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRTVShowsSortSelectorStateLayer.h>

@interface BRTVShowsSortSelectorStateLayer (Private)
- (id)_loadTextureWithKey:(id)fp8 orFromPNGFile:(id)fp12;
- (void)_buildDateSortWidget;
- (void)_buildShowSortWidget;
- (void)_buildUnselectedWidget;
- (void)_updateFrame;
@end

