/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderLayer.h>

@class BRImageLayer, BRTextLayer;

@interface BRTVShowsSortSelectorStateLayer : BRRenderLayer
{
    BRImageLayer *_leftEndCapLayer;	// 56 = 0x38
    BRImageLayer *_rightEndCapLayer;	// 60 = 0x3c
    BRImageLayer *_dividerLayer;	// 64 = 0x40
    BRImageLayer *_leftCenterLayer;	// 68 = 0x44
    BRImageLayer *_rightCenterLayer;	// 72 = 0x48
    BRTextLayer *_dateLayer;	// 76 = 0x4c
    BRTextLayer *_showLayer;	// 80 = 0x50
}

+ (id)dateSortWidgetWithScene:(id)fp8;
+ (id)showSortWidgetWithScene:(id)fp8;
+ (id)unselectedWidgetWithScene:(id)fp8;
- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (struct _NSSize)preferredSizeForScreenHeight:(float)fp8;
- (void)setFrame:(struct _NSRect)fp8;

@end

