/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRRenderLayer, BRTVShowsSortSelectorStateLayer;

@interface BRTVShowsSortControl : BRControl
{
    BRRenderLayer *_masterLayer;	// 8 = 0x8
    BRTVShowsSortSelectorStateLayer *_sortedByDateWidget;	// 12 = 0xc
    BRTVShowsSortSelectorStateLayer *_sortedByShowWidget;	// 16 = 0x10
    BRTVShowsSortSelectorStateLayer *_unselectedWidget;	// 20 = 0x14
    int _state;	// 24 = 0x18
}

- (id)initWithScene:(id)fp8 state:(int)fp12;
- (void)dealloc;
- (struct _NSSize)preferredSizeForScreenHeight:(float)fp8;
- (void)setFrame:(struct _NSRect)fp8;
- (id)layer;
- (BOOL)brEventAction:(id)fp8;

@end

