/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMediaMenuController.h>

#import "BRMenuListItemProviderProtocol.h"

@class BRMetadataPreviewController, BRTVShowsSortControl, NSArray;

@interface BRTVShowsController : BRMediaMenuController <BRMenuListItemProvider>
{
    NSArray *_headerRows;	// 108 = 0x6c
    NSArray *_mediaAssets;	// 112 = 0x70
    NSArray *_mediaCollections;	// 116 = 0x74
    BRTVShowsSortControl *_sortWidget;	// 120 = 0x78
    BRMetadataPreviewController *_cachedMDController;	// 124 = 0x7c
    int _sortState;	// 128 = 0x80
}

- (id)initWithScene:(id)fp8 error:(id *)fp12;
- (void)dealloc;
- (BOOL)shouldRefreshForUpdateToObject:(id)fp8;
- (id)musicStoreBaseType;
- (BOOL)isVolatile;
- (void)refreshControllerForModelUpdate;
- (id)loadModelData;
- (long)defaultIndex;
- (struct _NSRect)listFrameForBounds:(struct _NSSize)fp8;
- (void)frameForTitleIcon:(struct _NSRect *)fp8 andText:(struct _NSRect *)fp12 forBounds:(struct _NSSize)fp16;
- (void)itemSelected:(long)fp8;
- (id)itemForRow:(long)fp8;
- (long)itemCount;
- (id)titleForRow:(long)fp8;
- (long)rowForTitle:(id)fp8;
- (id)previewControllerForItem:(long)fp8;

@end

