/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRAnimation.h>

@class NSNumber, NSString;

@interface BRValueAnimation : BRAnimation
{
    NSNumber *_from;	// 60 = 0x3c
    NSNumber *_to;	// 64 = 0x40
    NSString *_key;	// 68 = 0x44
    id _target;	// 72 = 0x48
    double _sweep;	// 76 = 0x4c
    double _fromValue;	// 84 = 0x54
    double _toValue;	// 92 = 0x5c
}

+ (id)fadeInAnimationWithTarget:(id)fp8 scene:(id)fp12;
+ (id)fadeOutAnimationWithTarget:(id)fp8 scene:(id)fp12;
- (void)dealloc;
- (void)setFromValue:(id)fp8;
- (id)fromValue;
- (void)setToValue:(id)fp8;
- (id)toValue;
- (void)setTarget:(id)fp8;
- (id)target;
- (void)setKey:(id)fp8;
- (id)key;
- (void)positionChanged:(float)fp8;

@end

