/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRVideoPlayerHostLayer.h>

@interface BRVideoPlayerHostLayer (RenderFrame)
- (void)_updateRenderFrame;
- (void)_updateBlankingList:(BOOL)fp8;
- (id)_generateBlurTextureForImage:(id)fp8 inContext:(id)fp12;
@end

