/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRVideoPlayerController.h>

@interface BRVideoPlayerController (ClosedCaptioning)
- (struct _NSRect)_closedCaptionFrame;
- (id)_addClosedCaptionLayer;
- (void)_handleCCBeginUpdate:(id)fp8;
- (void)_handleCCEndUpdate:(id)fp8;
- (void)_handleCCEraseRow:(id)fp8;
- (void)_handleCCDisplayRow:(id)fp8;
@end

