/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRVideoPlayerController.h>

@interface BRVideoPlayerController (ResumeMenu)
- (long)_resumeTime;
- (void)_updateResumeTime;
- (void)_addResumeMenu;
- (void)_fadeResumeMenu;
- (void)_removeResumeMenu;
- (struct _NSRect)_resumeMenuFrame;
- (void)_resumeMenuSelection:(id)fp8;
@end

