/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMediaPlayer.h>

@class BRRenderContext;

@interface BRVideoPlayer : BRMediaPlayer
{
    BRRenderContext *_context;	// 8 = 0x8
    struct _NSSize _contextSize;	// 12 = 0xc
    unsigned int _enableCaptions:1;	// 20 = 0x14
    unsigned int _loops:1;	// 20 = 0x14
}

- (id)init;
- (void)dealloc;
- (BOOL)prerollMedia:(id *)fp8;
- (void)setPlaybackContext:(id)fp8;
- (id)playbackContext;
- (void)setContextSizeHint:(struct _NSSize)fp8;
- (struct _NSSize)contextSizeHint;
- (BOOL)newFrameForTime:(const CVTimeStamp *)fp8 frame:(struct __CVBuffer **)fp12;
- (struct __CVBuffer *)currentFrame;
- (float)aspectRatio;
- (void)setMovieLoops:(BOOL)fp8;
- (BOOL)movieLoops;
- (void)setCaptionsEnabled:(BOOL)fp8;
- (BOOL)captionsEnabled;
- (struct BRVideoTimeRange)bufferedRange;

@end

