/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRVideoHardwarePostprocessor.h>

@interface BRVideoHardwarePostprocessor (ColorSync)
- (void)_updateColorSyncDataForFrame:(struct __CVBuffer *)fp8;
@end

