/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRVideoLoadMonitor.h>

@class NSTimer, QTMovie;

@interface BRVideoStandardLoadMonitor : BRVideoLoadMonitor
{
    QTMovie *_movie;	// 4 = 0x4
    int _waitState;	// 8 = 0x8
    NSTimer *_loadPoll;	// 12 = 0xc
    BRKeyFrame _loadTarget;	// 16 = 0x10
    unsigned int _playable:1;	// 32 = 0x20
    unsigned int _loaded:1;	// 32 = 0x20
}

- (id)initWithMovie:(id)fp8;
- (void)dealloc;
- (void)stopMonitoring;
- (BOOL)moviePlayable;
- (BOOL)movieLoaded;
- (float)bufferingProgress;
- (struct BRVideoTimeRange)bufferedRange;
- (double)maxMovieTime;

@end

