/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class BRRenderContext;

@interface BRVideoHardwarePostprocessor : NSObject
{
    BRRenderContext *_context;	// 4 = 0x4
    struct BRPostProcessMatrix _matrix709;	// 8 = 0x8
    struct BRPostProcessMatrix _matrix601;	// 136 = 0x88
    unsigned int _vpName;	// 264 = 0x108
    unsigned int _fpNames[32];	// 268 = 0x10c
    unsigned int _noiseTexName;	// 396 = 0x18c
    int _fpIndex;	// 400 = 0x190
    int _forceFPBitsOff;	// 404 = 0x194
    int _forceFPBitsOn;	// 408 = 0x198
    struct CGColorSpace *_colorsync_cachedspaceref;	// 412 = 0x19c
    struct CGColorSpace *_to_spaceref;	// 416 = 0x1a0
    int _tdBitDepth;	// 420 = 0x1a4
    float _tdOnFrame;	// 424 = 0x1a8
    unsigned long long _noiseSeedTime;	// 428 = 0x1ac
    float _noiseParamX;	// 436 = 0x1b4
    float _noiseParamY;	// 440 = 0x1b8
    struct BRVideoColorSyncData _cSyncData;	// 444 = 0x1bc
}

- (id)initWithContext:(id)fp8;
- (void)dealloc;
- (void)renderFrame:(struct __CVBuffer *)fp8 fromTime:(unsigned long long)fp12 inRect:(struct _NSRect)fp20;

@end

