/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class BRVideoLoadMonitor, NSArray, QTMovie;

@interface BRVideo : NSObject
{
    struct OpaqueQTVisualContext *_textureContext;	// 4 = 0x4
    struct __CVBuffer *_currentFrame;	// 8 = 0x8
    BRVideoLoadMonitor *_loadMonitor;	// 12 = 0xc
    struct _NSSize _contextSizeHint;	// 16 = 0x10
    id _media;	// 24 = 0x18
    struct TrackType **_movieTrack;	// 28 = 0x1c
    QTMovie *_movie;	// 32 = 0x20
    float _rate;	// 36 = 0x24
    long _chapterTimeScale;	// 40 = 0x28
    NSArray *_chapters;	// 44 = 0x2c
    double _prevScanTime;	// 48 = 0x30
    double _movieScanPosition;	// 56 = 0x38
    double _timeFreq;	// 64 = 0x40
    struct BRVideoTimeRange _bufferedRange;	// 72 = 0x48
    float _bufferingProgress;	// 88 = 0x58
    double _movieDuration;	// 92 = 0x5c
    double _movieTime;	// 100 = 0x64
    long _cachedChapterIndex;	// 108 = 0x6c
    unsigned int _captionsEnabled:1;	// 112 = 0x70
    struct BRVideoPlaybackStats _stats;	// 116 = 0x74
    unsigned int _gatherStats:1;	// 132 = 0x84
    unsigned int _loops:1;	// 132 = 0x84
    unsigned int _muted:1;	// 132 = 0x84
}

- (id)init;
- (id)initWithMedia:(id)fp8 error:(id *)fp12;
- (id)media;
- (void)dealloc;
- (void)setPlaybackContext:(id)fp8;
- (void)skip:(double)fp8;
- (void)setElapsedTime:(double)fp8;
- (double)elapsedTime;
- (double)duration;
- (float)aspectRatio;
- (float)bufferingProgress;
- (struct BRVideoTimeRange)bufferedRange;
- (BOOL)videoPlayable;
- (void)gotoBeginning;
- (BOOL)newFrameForTime:(const CVTimeStamp *)fp8 frame:(struct __CVBuffer **)fp12;
- (struct __CVBuffer *)currentFrame;
- (struct _NSSize)setContextSize:(struct _NSSize)fp8;
- (void)setMuted:(BOOL)fp8;
- (BOOL)muted;
- (void)setLoops:(BOOL)fp8;
- (BOOL)loops;
- (void)setCaptionsEnabled:(BOOL)fp8;
- (BOOL)captionsEnabled;
- (void)setRate:(float)fp8;
- (float)rate;
- (id)chapterList;
- (long)currentChapterIndex;
- (void)setGatherPlaybackStats:(BOOL)fp8;
- (struct BRVideoPlaybackStats)playbackStats;

@end

