/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderLayer.h>

@class BRQuadLayer, BRTextLayer, NSDictionary, NSString;

@interface BRVideoPlayerStatisticsLayer : BRRenderLayer
{
    struct BRVideoPlaybackStats _stats;	// 56 = 0x38
    NSString *_location;	// 72 = 0x48
    BRQuadLayer *_background;	// 76 = 0x4c
    BRTextLayer *_locationField;	// 80 = 0x50
    BRTextLayer *_movieDimensionsField;	// 84 = 0x54
    BRTextLayer *_droppedFrameCountField;	// 88 = 0x58
    BRTextLayer *_hardwareCodecInUseField;	// 92 = 0x5c
    BRTextLayer *_postProcessingField;	// 96 = 0x60
    NSDictionary *_singleLineAttributes;	// 100 = 0x64
    NSDictionary *_multiLineAttributes;	// 104 = 0x68
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)setFrame:(struct _NSRect)fp8;
- (void)setAlphaValue:(float)fp8;
- (void)setLocation:(id)fp8;
- (void)setStats:(struct BRVideoPlaybackStats)fp8;
- (struct _NSSize)minimumSize;

@end

