/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRWaitSpinnerLayer;

@interface BRWaitSpinnerControl : BRControl
{
    BRWaitSpinnerLayer *_layer;	// 8 = 0x8
}

- (id)initWithScene:(id)fp8;
- (void)dealloc;
- (void)startSpinning;
- (void)stopSpinning;
- (id)layer;

@end

