/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderer.h>

@class BRRenderContext, BRRenderScene;

@interface BRWindowRenderer : BRRenderer
{
    struct CGRect _frame;	// 4 = 0x4
    void *_window;	// 20 = 0x14
    BRRenderScene *_scene;	// 24 = 0x18
    BRRenderContext *_context;	// 28 = 0x1c
    unsigned int _draggable:1;	// 32 = 0x20
    unsigned int _opaque:1;	// 32 = 0x20
}

- (id)init;
- (void)dealloc;
- (id)scene;
- (void)orderIn;
- (void)orderOut;
- (void *)createDVDWindow;
- (void)destroyDVDWindow:(void *)fp8;

@end

