/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRXHardwareUtility.h>

@interface BRXHardwareUtility (Private)
- (BOOL)_isEmbeddedHardwareDevice;
- (void)_turnLEDOn:(int)fp8;
- (void)_turnLEDOff:(int)fp8;
- (void)_turnOffLEDs;
- (void)_blinkWhiteLED;
- (void)_blinkAmberLED;
- (BOOL)_determineIfEmbeddedHardwareDevice;
@end

