/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRXSWUpdateManager.h>

@interface BRXSWUpdateManager (LockedAccess)
- (void)_setCheckInProgress:(BOOL)fp8;
- (void)_setDownloadInProgress:(BOOL)fp8;
- (BOOL)_downloadingAFile;
- (void)_setDownloadAFile:(BOOL)fp8;
- (id)_downloadError;
- (void)_setDownloadError:(id)fp8;
- (void)_setCancelRequest:(BOOL)fp8;
- (BOOL)_wasCancelRequested;
@end

