/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@class BRXSWUpdateRecord, BRXUpdateVerifier, NSDate, NSError, NSLock, NSMutableArray, NSTimer;

@interface BRXSWUpdateManager : BRSingleton
{
    NSTimer *_updateCheckTimer;	// 4 = 0x4
    NSDate *_lastCheckTime;	// 8 = 0x8
    NSDate *_nextCheckTime;	// 12 = 0xc
    unsigned int _checkInProgress:1;	// 16 = 0x10
    unsigned int _downloadInProgress:1;	// 16 = 0x10
    unsigned int _singleFileDownloadInProgress:1;	// 16 = 0x10
    unsigned int _installUpdates:1;	// 16 = 0x10
    unsigned int _automaticUpdateTriggered:1;	// 16 = 0x10
    unsigned int _cancelRequested:1;	// 16 = 0x10
    NSError *_downloadError;	// 20 = 0x14
    BRXSWUpdateRecord *_pendingRecord;	// 24 = 0x18
    NSMutableArray *_licenses;	// 28 = 0x1c
    NSMutableArray *_payloads;	// 32 = 0x20
    BRXUpdateVerifier *_verifier;	// 36 = 0x24
    NSLock *_accessLock;	// 40 = 0x28
}

+ (id)singleton;
+ (void)setSingleton:(id)fp8;
- (id)init;
- (void)dealloc;
- (void)startMonitoring;
- (void)stopMonitoring;
- (BOOL)checkForUpdates;
- (BOOL)updateCheckInProgress;
- (BOOL)updateDownloadInProgress;
- (void)applyUpdatesIfAvailable;
- (void)cancelUpdates;
- (id)localUpdateFolderPath;
- (void)updatesPostponed;

@end

