/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRXSWUpdateManager.h>

@interface BRXSWUpdateManager (NSURLDownloadDelegate)
- (void)downloadDidBegin:(id)fp8;
- (id)download:(id)fp8 willSendRequest:(id)fp12 redirectResponse:(id)fp16;
- (void)download:(id)fp8 willResumeWithResponse:(id)fp12 fromByte:(long long)fp16;
- (void)download:(id)fp8 didReceiveDataOfLength:(unsigned int)fp12;
- (BOOL)download:(id)fp8 shouldDecodeSourceDataOfMIMEType:(id)fp12;
- (void)download:(id)fp8 decideDestinationWithSuggestedFilename:(id)fp12;
- (void)download:(id)fp8 didCreateDestination:(id)fp12;
- (void)downloadDidFinish:(id)fp8;
- (void)download:(id)fp8 didFailWithError:(id)fp12;
@end

