/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRXSWUpdateApplyController.h>

#import "BRXSWUpdateConfirmDelegateProtocol.h"

@interface BRXSWUpdateApplyController (Callbacks) <BRXSWUpdateConfirmDelegate>
- (void)updateConfirmed:(BOOL)fp8;
@end

