/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRXSWUpdateManager.h>

@interface BRXSWUpdateManager (Downloading)
- (void)_startCheckTimer;
- (void)_stopCheckTimer;
- (void)_setNextCheckTime;
- (void)_checkForUpdates:(id)fp8;
- (void)_performUpdateCheck;
- (BOOL)_downloadAndVerifyUpdates:(id *)fp8;
- (id)_downloadFileForURL:(id)fp8 andVerify:(BOOL)fp12 error:(id *)fp16;
- (id)_localFileForURL:(id)fp8 error:(id *)fp12;
- (void)_cleanUpFiles;
- (id)_localFilePathForUpdateURL:(id)fp8;
- (void)_collectDownloadURLsFrom:(id)fp8 intoPayloads:(id)fp12 licenses:(id)fp16 readmes:(id)fp20;
- (BOOL)_shouldVerifyFile:(id)fp8;
@end

