/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSDictionary, NSString;

@interface BRXSWUpdateRecord : NSObject
{
    NSString *_currentOSVersion;	// 4 = 0x4
    NSString *_currentOSBuildVersion;	// 8 = 0x8
    NSString *_currentEFIVersion;	// 12 = 0xc
    NSString *_currentIRVersion;	// 16 = 0x10
    NSString *_currentSIMainVersion;	// 20 = 0x14
    NSString *_currentSIBootVersion;	// 24 = 0x18
    NSString *_newOSVersion;	// 28 = 0x1c
    NSString *_newOSBuildVersion;	// 32 = 0x20
    NSString *_newEFIVersion;	// 36 = 0x24
    NSString *_newIRVersion;	// 40 = 0x28
    NSString *_newSIMainVersion;	// 44 = 0x2c
    NSString *_newSIBootVersion;	// 48 = 0x30
    NSDictionary *_osUpdateURLs;	// 52 = 0x34
    NSDictionary *_efiUpdateURLs;	// 56 = 0x38
    NSDictionary *_irUpdateURLs;	// 60 = 0x3c
    NSDictionary *_siUpdateURLs;	// 64 = 0x40
    unsigned int _autoUpdate:1;	// 68 = 0x44
    unsigned int _SIImageValid:1;	// 68 = 0x44
}

- (id)initWithVersionData:(id)fp8 autoUpdate:(BOOL)fp12;
- (void)dealloc;
- (id)description;
- (BOOL)osUpdateAvailable;
- (BOOL)efiUpdateAvailable;
- (BOOL)irUpdateAvailable;
- (BOOL)siMainUpdateAvailable;
- (BOOL)siBootUpdateAvailable;
- (BOOL)anyUpdateAvailable;
- (BOOL)autoUpdate;
- (id)newOSVersion;
- (id)newOSBuildVersion;
- (id)newEFIVersion;
- (id)newIRVersion;
- (id)newSIMainVersion;
- (id)newSIBootVersion;
- (id)osUpdateURLs;
- (id)efiUpdateURLs;
- (id)irUpdateURLs;
- (id)siUpdateURLs;

@end

