/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRCenteredMenuController.h>

#import "BRMenuListItemProviderProtocol.h"

@class BRBackgroundLayer, BRXSWUpdateRecord;

@interface BRXSWUpdateConfirmController : BRCenteredMenuController <BRMenuListItemProvider>
{
    BRBackgroundLayer *_background;	// 136 = 0x88
    BRXSWUpdateRecord *_record;	// 140 = 0x8c
    id _delegate;	// 144 = 0x90
    unsigned int _readyToInstall:1;	// 148 = 0x94
}

- (id)initWithScene:(id)fp8 forUpdate:(id)fp12 readyToInstall:(BOOL)fp16 notifying:(id)fp20;
- (void)dealloc;
- (void)wasPushed;
- (void)itemSelected:(long)fp8;
- (id)itemForRow:(long)fp8;
- (long)itemCount;
- (id)titleForRow:(long)fp8;
- (long)rowForTitle:(id)fp8;
- (BOOL)brEventAction:(id)fp8;
- (void)resetLayout;

@end

