/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRLayerController.h>

@class BRXSWUpdateRecord, NSMutableArray;

@interface BRXSWUpdateApplyController : BRLayerController
{
    BRXSWUpdateRecord *_record;	// 24 = 0x18
    NSMutableArray *_licenses;	// 28 = 0x1c
    unsigned int _updatePostponed:1;	// 32 = 0x20
}

- (id)initWithScene:(id)fp8 forUpdate:(id)fp12 showingLicenses:(id)fp16;
- (void)dealloc;
- (void)wasPushed;
- (void)wasExhumedByPoppingController:(id)fp8;

@end

