/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRXUpdateVerifier.h>

@interface BRXUpdateVerifier (Private)
- (struct cssm_key *)_publicKey;
- (long)_verifyDataInFile:(id)fp8 usingContext:(unsigned long long)fp12;
- (long)_verifySignatureInFile:(id)fp8 usingContext:(unsigned long long)fp12;
@end

