/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@interface BRXVersionInfo : NSObject
{
}

+ (id)currentOSVersion;
+ (id)currentOSBuildVersion;
+ (int)compareOSVersion:(id)fp8 andBuild:(id)fp12 withOSVersion:(id)fp16 andBuild:(id)fp20;
+ (id)currentEFIVersion;
+ (int)compareEFIVersion:(id)fp8 withEFIVersion:(id)fp12;
+ (id)currentIRVersion;
+ (int)compareIRVersion:(id)fp8 withIRVersion:(id)fp12;
+ (id)currentSIMainVersion;
+ (id)currentSIBootVersion;
+ (BOOL)isSIFirmwareValid;
+ (int)compareSIVersion:(id)fp8 withSIVersion:(id)fp12;

@end

