/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

struct AuthorizationOpaqueRef;

struct BRBitmapDataInfo {
    unsigned int internalFormat;
    unsigned int dataFormat;
    unsigned int dataType;
    unsigned int width;
    unsigned int height;
};

struct BRDisplayStringMappingEntry {
    unsigned int _field1;
    unsigned int _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
    float _field6;
    char _field7;
    char _field8;
    id *_field9;
};

struct BRGlyphLocation {
    int x;
    int y;
};

struct BRPhloatoPlaneImagePosition {
    float _field1;
    float _field2;
};

struct BRPostProcessMatrix {
    double m[4][4];
};

struct BRTextureInfo {
    unsigned int textureID;
    unsigned int target;
    struct _NSSize size;
    float topLeft[2];
    float topRight[2];
    float bottomLeft[2];
    float bottomRight[2];
};

struct BRVideoColorSyncData {
    float addvector[4];
    float matrix[3][4];
    float gamma1[4];
    float gamma2[4];
    float a1[4];
    float b1[4];
    float c1[4];
    float d1[4];
    float e1[4];
    float f1[4];
    float a2[4];
    float b2[4];
    float c2[4];
    float d2[4];
    float e2[4];
    float f2[4];
};

struct BRVideoPlaybackStats {
    long stallCount;
    struct _NSSize movieDimensions;
    char hardwareCodec;
    char needsPostprocessing;
};

struct BRVideoTimeRange {
    double location;
    double length;
};
/*
struct CGColor;

struct CGColorSpace;

struct CGContext;

struct CGImage;

struct CGPoint {
    float x;
    float y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    float width;
    float height;
};

struct CVSMPTETime {
    short _field1;
    short _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
    short _field6;
    short _field7;
    short _field8;
    short _field9;
};

struct FSRef {
    unsigned char _field1[80];
};
*/
struct OpaqueQTVisualContext;

struct SHLanguageData {
    char _field1[100];
};

struct SHNetworkData {
    int _field1;
    int _field2;
    char _field3[16];
    char _field4[16];
    char _field5[16];
    char _field6[16];
};

struct SHPowerData {
    int _field1;
};

struct SHRestoreData {
    int _field1;
};

struct SHTimeZoneData {
    int _field1;
};

struct SHUpdateData {
    int _field1;
    int _field2;
    int _field3;
    int _field4;
};

struct SHWatchdogData {
    int _field1;
};

struct SHCommandInfo {
    unsigned int _field1;
    union {
        struct SHLanguageData _field1;
        struct SHNetworkData _field2;
        struct SHPowerData _field3;
        struct SHTimeZoneData _field4;
        struct SHUpdateData _field5;
        struct SHRestoreData _field6;
        struct SHWatchdogData _field7;
    } _field2;
};

struct TrackType;

struct _Apple80211;

struct _CGDirectDisplayID;

struct _CGLContextObject;

struct _CGLPBufferObject;

struct _CGLPixelFormatObject;
/*
struct _NSPoint {
    float x;
    float y;
};

struct _NSRange {
    unsigned int location;
    unsigned int length;
};

struct _NSRect {
    struct _NSPoint origin;
    struct _NSSize size;
};

struct _NSSize {
    float width;
    float height;
};
*/
struct _NSZone;

struct __CFRunLoop;

struct __CFRunLoopSource;

struct __CTFont;

struct __CTFramesetter;

struct __CTLine;

struct __CTTextTab;

struct __CTTypesetter;

struct __CVBuffer;

struct __CVDisplayLink;

struct __SCDynamicStore;

struct __SCNetworkService;

struct cssm_data {
    unsigned int Length;
    char *Data;
};

struct cssm_date {
    unsigned char Year[4];
    unsigned char Month[2];
    unsigned char Day[2];
};

struct cssm_guid {
    unsigned int Data1;
    unsigned short Data2;
    unsigned short Data3;
    unsigned char Data4[8];
};

struct cssm_keyheader {
    unsigned int HeaderVersion;
    struct cssm_guid CspId;
    unsigned int BlobType;
    unsigned int Format;
    unsigned int AlgorithmId;
    unsigned int KeyClass;
    unsigned int LogicalKeySizeInBits;
    unsigned int KeyAttr;
    unsigned int KeyUsage;
    struct cssm_date StartDate;
    struct cssm_date EndDate;
    unsigned int WrapAlgorithmId;
    unsigned int WrapMode;
    unsigned int Reserved;
};

struct cssm_key {
    struct cssm_keyheader _field1;
    struct cssm_data _field2;
};

// CVTimeStamp structure from <CoreVideo/CVBase.h>
/*
typedef struct {
    unsigned int _field1;
    int _field2;
    long long _field3;
    unsigned long long _field4;
    double _field5;
    long long _field6;
    struct CVSMPTETime _field7;
    unsigned long long _field8;
    unsigned long long _field9;
} CDAnonymousStruct1;
*/

typedef struct {
    long long timeValue;
    long timeScale;
    long flags;
} BRKeyFrame;

