/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSString.h>

@interface NSString (RUIStringUtilities)
+ (id)stringWithAppleScriptLines:(id)fp8;
+ (id)timeStringForTVShowsFromSeconds:(long)fp8;
- (id)stringByRemovingStopWordPrefixes:(id)fp8;
- (id)stringByReplacingStopWordPrefixes:(id)fp8;
- (int)customCompareIgnoringPrefixes:(id)fp8;
- (int)customCompare:(id)fp8;
- (unsigned long)hexValue;
@end

