/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@interface RUIPowerManager : NSObject
{
    unsigned int _rootPowerSource;	// 4 = 0x4
}

+ (id)sharedManager;
- (id)init;
- (void)_powerCallback:(void *)fp8:(unsigned int)fp12:(unsigned int)fp16:(void *)fp20;

@end

